export type {
  UiLocale,
  HookEventPayload,
  NodeStatus,
  ToolDurationEntry,
  DiagnosticEntry,
  CompactCount,
  RateLimitInfo,
  ClaudeUsageLimit,
  ClaudeUsageExtraCredits,
  ClaudeUsageSource,
  ClaudeUsageError,
  ClaudeUsageInfo,
  ClaudeAuthStatus,
  ClaudeAuthProbeError,
  ClaudeAuthLoginMode,
  UsageCollectorStatus,
  BubbleType,
  CaptureSourceKind,
  CaptureSourceInfo,
  AppBubble,
  CaptureBubble,
  PlayRecipeKind,
  PlayRecipeSource,
  PlayBubbleStatus,
  PlayRecipe,
  PlayRecipeCandidate,
  PlayBubble,
  SpecItem,
  SpecDoc,
  ReviewFileChangeType,
  ReviewFileChange,
  ReviewDecisionKind,
  ReviewDecision,
  ReviewRequestStatus,
  ReviewRequest,
  LabVariantConfig,
  LabResultStatus,
  LabResult,
  LabVariant,
  LabRunStatus,
  LabRun,
  ShelfItemKind,
  ShelfRunStatus,
  ShelfIconName,
  ShelfItemRun,
  ShelfItem,
  ShelfBubble,
  ShelfExportItem,
  ShelfExport,
  CostTotals,
  CostPeriod,
  CostPeriodTotals,
  CostDayBucket,
  CostSessionEntry,
  CostAgentTotal,
  ProjectCostMap,
  AuditRiskKind,
  AuditDecisionSource,
  AuditEntry,
  AuditBoundaryConfig,
  AuditRetired,
  AuditCounts,
  ProjectAuditLog,
  CaptureMouseInput,
  CaptureKeyInput,
  CaptureInputEvent,
  CaptureTargetRect,
  CaptureInjectResult,
  BubbleStyleConfig,
  EdgeStyleConfig,
  BubbleData,
  ActivityEdge,
  AgentStatus,
  WSMessageType,
  WSMessage,
  PermissionRequest,
  PermissionDecision,
  AskUserQuestionRequest,
  AskUserQuestionDecision,
  AskUserQuestionAnswer,
  AskUserQuestionOption,
  AskUserQuestionItem,
  AskUserQuestionToolInput,
  AgentReport,
  AgentQuestionItem,
  AgentQuestions,
  AgentReview,
  AgentList,
  AgentFeedbackVerdict,
  AgentFeedbackTargetType,
  AgentFeedback,
  BrainCardType,
  BrainCardScope,
  BrainCardStatus,
  BrainVerifyState,
  BrainAuthority,
  BrainObservation,
  BrainAppliesTo,
  BrainCurrentEntry,
  BrainAnchor,
  BrainCard,
  BrainCardInput,
  BrainSaveOutcome,
  BrainSaveResult,
  BrainSummary,
  BrainInjectionEvent,
  BrainFeedSectionKey,
  BrainFeed,
  BrainTopicDef,
  BrainTopicIndexEntry,
  BrainMigrationNote,
  BrainMigrationKeySuggestion,
  BrainMigrationDuplicateGroup,
  BrainMigrationConflictPair,
  BrainMigrationCounts,
  BrainMigrationReport,
  BrainAxisId,
  BrainActivation,
  BrainSkillStatus,
  BrainSkill,
  BrainRecallHit,
  GraphSnapshot,
  GraphSnapshotWire,
  GraphSnapshotDeltas,
  KeyedSliceDelta,
  Result,
  BashEntry,
  FileEdit,
  ServerEntry,
  AgentEvent,
  TodoItem,
  StreamDensity,
  QueuedCommand,
  CommandDispatchMode,
  CommandErrorCode,
  CommandError,
  SessionLoop,
  SessionLoopMode,
  SessionLoopStatus,
  SessionLoopContextMode,
  VerificationRun,
  VerificationRunStatus,
  VerificationRecipeSource,
  VerificationAttemptRecord,
  VerifyVerdict,
  VerificationDemo,
  VerificationDemoStep,
  VerificationDemoFrame,
  SessionGoal,
  SessionGoalStatus,
  SessionGoalStep,
  SessionGoalStepStatus,
  SessionGoalProgress,
  SessionGoalProgressSource,
  ContextSourceCategory,
  ContextSourceControl,
  ContextSourceChild,
  ContextSourceItem,
  ContextInventory,
  ContextOverrideMap,
  ContextOverrides,
  ContextSourcePreview,
  SubAgent,
  SubAgentStatus,
  SessionMemo,
  SubAgentHistoryItem,
  RunningSubagentTask,
  FinishedSubagentTask,
  AgentPhase,
  ProjectInfo,
  EdgeSnapshot,
  ProjectMeta,
  FolderFileEntry,
  WorkspaceEntry,
  WorkspaceDirListing,
  WorkspacePathKind,
  WorkspacePathInfo,
  ExternalPathInfo,
  WorkspaceEol,
  WorkspaceFileContent,
  WorkspaceFileSaveRequest,
  WorkspaceFileSaveResult,
  WorkspaceImageSaveRequest,
  WorkspaceEntryCreateRequest,
  WorkspaceEntryRenameRequest,
  WorkspaceEntryMoveRequest,
  WorkspaceEntryDeleteRequest,
  WorkspaceEntryResult,
  WorkspaceEntryDeleteResult,
  ProjectCheckpoint,
  ProjectIdentity,
  GhostChangeType,
  GhostInfo,
  ServerKind,
  TurnTokenUsage,
  TokenCategoryEstimate,
  SessionTokenData,
  PipelineType,
  AgentRole,
  PipelineChildConfig,
  PipelineState,
  AgentConfig,
  AgentDefinition,
  ExecutionMode,
  CmdCliKind,
  CmdTerminalState,
  CmdTerminalSignal,
  CmdPaneLeaf,
  CmdPaneSplit,
  CmdPaneNode,
  ModelFamily,
  KnownModelFamily,
  ModelRegistry,
  ModelRegistryEntry,
  BuiltinSlashCommand,
  UserDefaults,
  UserNotificationDefaults,
  UserAdvancedDefaults,
  PluginContributionKind,
  PluginCategory,
  PluginManifest,
  PluginFactMap,
  StreamEventType,
  SubAgentStreamEvent,
  TaskEdgeStatus,
  TaskEdgeForwardMode,
  TaskEdgeKind,
  TaskEdgeMessageFormat,
  TaskEdgeReturnFormat,
  TaskEdgePriority,
  TaskEdgeCritiqueTiming,
  TaskEdgeCritiqueAuthority,
  TaskEdgeCommandMode,
  TaskEdge,
  TaskEdgeTemplate,
  SessionSource,
  SessionLifeStatus,
  GitStatus,
  GitCommit,
  GitWorktreeStatus,
  PreviewPickPayload,
  PreviewDevicePreset,
  PreviewSnipRect,
  PageRegionCapture,
  ProjectMetaSnapshot,
  HydrateProjectPayload,
  ProjectHydratedPayload,
  UnloadProjectPayload,
  ProjectUnloadedPayload,
  SetProjectScopePayload,
  ProjectAgentCounts,
  IframeLogLevel,
  IframeLogLine,
  IframeLogSubscribePayload,
  IframeLogUnsubscribePayload,
  IframeLogInitPayload,
  IframeLogAppendPayload,
  ServerLogLevel,
  ServerLogCategory,
  ServerLogEntry,
  ServerLogSubscribePayload,
  ServerLogUnsubscribePayload,
  ServerLogInitPayload,
  ServerLogAppendPayload,
  AppState,
  AppStatePatch,
  RetentionSettings,
  RetentionLogEntry,
  StorageUsageKind,
  StorageUsageEntry,
  ProjectStorageUsage,
  WorktreeStorageUsage,
  StorageUsageReport,
  StorageCleanupResult,
  CommentBox,
  ContiCustomMode,
  AgentMemoryScope,
  ContiElementType,
  ContiElement,
  ContiFrame,
  ContiBadge,
  Conti,
  ContiEventPayload,
  ContiWorkSource,
  ActiveContiWork,
  ContiSource,
  ContiRenderLink,
  ContiRenderStatus,
  StoryboardPresetId,
  StoryboardPreset,
  RulesHistoryEntry,
  CanvasClipboardAgentEntry,
  CanvasClipboardTaskEdgeEntry,
  CanvasClipboardCommentBoxEntry,
  CanvasClipboardPayload,
  CanvasPasteResponse,
  ClaudeVersionInfo,
  ClaudeInstallProgress,
  // §5.19 All Model — 로컬 LLM
  AgentProviderKind,
  AgentProvider,
  LocalEngineBackend,
  LocalEngineProgress,
  LocalEngineState,
  LocalModelEntry,
  LocalModelDownloadProgress,
  LocalModelCatalogEntry,
  LocalDeviceInfo,
  LocalHardwareInfo,
  LocalModelFit,
  LocalModelCatalogRepo,
  LocalModelCatalogSort,
  LocalLlmState,
  ClaudeInstall,
  ClaudeInstallsInfo,
  ClaudeBinSource,
  ClaudeSetupPhase,
  ClaudeSetupState,
  ClaudeSetupProgress,
  AgentViewRosterEntry,
  AgentViewJobState,
  AutoAgentRole,
  AutoAgentTopology,
  AutoAgentComplexity,
  AutoAgentPhase,
  AutoAgentTemplate,
  AutoAgentClarifyingQuestion,
  AutoAgentSummary,
  AutoAgentRun,
  AutoAgentRunStatus,
  VerificationAttempt,
  VerificationKind,
  VerificationVerdict,
  EscalationReason,
  UpdatePhase,
  UpdateDelivery,
  UpdateState,
  UpdateErrorCode,
  MobileAccessState,
  MobileQrTicket,
  MobileExternalStatus,
  MobileExternalReason,
  ChatChannelKind,
  ChatVerbosity,
  ChatChannelStatus,
  ChatChannelError,
  ChatPeer,
  ChatPairTicket,
  ChatChannelState,
  ChatBridgeState,
  ChatAction,
  ChatCard,
  TermCreateFrame,
  TermWriteFrame,
  TermResizeFrame,
  TermKillFrame,
  TermDataFrame,
  TermExitFrame,
  TermAckFrame,
  TermUnavailableFrame,
} from './types.js';

export type { ModelPricing } from './constants.js';
/** §5.19 (H) — 로컬 도구 한 건의 처리 방식(allow/ask/deny). */
export type { LocalToolGate } from './constants.js';

export {
  DEFAULT_PORT,
  WS_PATH,
  MAX_RECONNECT_ATTEMPTS,
  RECONNECT_BASE_DELAY,
  WS_BATCH_INTERVAL,
  WS_STREAM_BATCH_INTERVAL,
  WS_BATCH_INTERVAL_MAX,
  WS_BATCH_BACKOFF_FACTOR,
  CHECKPOINT_BATCH_INTERVAL,
  CHECKPOINT_BATCH_INTERVAL_MAX,
  CHECKPOINT_QUIET_SWEEP_MS,
  BUBBLE_STYLES,
  HOOK_AGENT_STYLE,
  BUBBLE_COLORS,
  READ_TOOLS,
  EDGE_STYLE,
  NODE_MIN_SIZE,
  NODE_MAX_SIZE,
  FILE_MIN_SIZE,
  FILE_MAX_SIZE,
  MAX_BASH_HISTORY,
  MAX_FILE_EDITS,
  MAX_WRITE_DIFF_BYTES,
  FILE_EDIT_RETENTION_DAYS,
  MAX_FILE_EDIT_PATHS,
  FILE_EDIT_MERGE_WINDOW_MS,
  COMPLETED_COMMAND_MAX_PER_SESSION,
  SUB_STREAM_RETENTION_DAYS,
  ATTACHMENT_RETENTION_DAYS,
  TRASH_RETENTION_DAYS,
  RETENTION_LOG_MAX,
  RETENTION_DAY_MS,
  DEFAULT_RETENTION_SETTINGS,
  RETENTION_LIMITS,
  normalizeRetentionSettings,
  isExpiredByDays,
  // §3.2.4 런타임 메모리 자정작용
  SESSION_CACHE_BYTE_BUDGET,
  SESSION_CACHE_MAX_ENTRIES,
  JSONL_SCAN_CHUNK_BYTES,
  MEMORY_SAMPLE_INTERVAL_MS,
  MEMORY_SAMPLE_HISTORY,
  MEMORY_PRESSURE_HIGH_RATIO,
  MEMORY_PRESSURE_CRITICAL_RATIO,
  MEMORY_PRESSURE_EVICT_FRACTION,
  MEMORY_PRESSURE_COOLDOWN_MS,
  SESSION_KEYED_MAP_MAX,
  DEFAULT_MAX_SATELLITES,
  SATELLITE_MAX_BOUNDS,
  WORKSPACE_DIR_ENTRY_MAX,
  WORKSPACE_FILE_MAX_BYTES,
  IDE_EDITOR_MAX_TABS,
  IDE_EDITOR_TAB_SCOPE_MAX,
  IDE_EDITOR_WIDTH,
  WORKSPACE_IMAGE_EXTENSIONS,
  WORKSPACE_IMAGE_BAKEABLE_EXTENSIONS,
  WORKSPACE_IMAGE_MAX_BYTES,
  WORKSPACE_IMAGE_MIME_BY_EXT,
  WORKSPACE_PDF_EXTENSIONS,
  WORKSPACE_EXTERNAL_EXTENSIONS,
  WORKSPACE_CONVERT_VIDEO_EXTENSIONS,
  WORKSPACE_CONVERT_AUDIO_EXTENSIONS,
  MEDIA_CACHE_DIR,
  mediaCacheRelPath,
  WORKSPACE_MEDIA_MIME_BY_EXT,
  WORKSPACE_MEDIA_MAX_BYTES,
  workspaceMediaMime,
  resolveWorkspaceOpen,
  workspaceFileExt,
  isWorkspaceImagePath,
  isWorkspaceImageBakeable,
  workspaceImageMime,
  MAX_AGENTS,
  MAX_AGENT_EVENTS,
  INITIAL_AGENT_COUNT,
  BUBBLE_TTL,
  AGENT_FADE_DURATION,
  SESSION_SCAN_INTERVAL,
  AGENT_IDLE_THRESHOLD_MS,
  SUBAGENT_DORMANT_IDLE_MS,
  AGENT_IDLE_SWEEP_INTERVAL_MS,
  PROJECT_IDLE_UNLOAD_MS,
  PROJECT_IDLE_UNLOAD_SWEEP_MS,
  PROJECT_IDLE_UNLOAD_PRESSURE_MS,
  PROJECT_LOAD_HINT_DELAY_MS,
  PROJECT_LOAD_HINT_SLOW_MS,
  INTERRUPT_RECONCILE_INTERVAL_MS,
  ZOMBIE_EXECUTING_GRACE_MS,
  FILE_EXISTENCE_CHECK_INTERVAL,
  FILE_EXISTENCE_MISS_THRESHOLD,
  AGENT_CLUSTER_BASE_RADIUS,
  AGENT_CLUSTER_RADIUS_PER_AGENT,
  ORBIT_BASE_RADIUS,
  ORBIT_RADIUS_PER_ITEM,
  SATELLITE_ORBIT_GAP,
  SATELLITE_TYPES,
  GHOST_FADE_DURATION,
  PANEL_DEFAULT_WIDTH,
  PANEL_MIN_WIDTH,
  PANEL_MAX_WIDTH,
  TCP_TIMEOUT,
  POSITION_SAVE_INTERVAL,
  CHECKPOINT_BACKUP_GENERATIONS,
  APP_STATE_BACKUP_GENERATIONS,
  DELETED_AGENT_TOMBSTONE_MAX,
  CHECKPOINT_EMPTY_GUARD_MIN_PRIOR,
  CHECKPOINT_SHRINK_GUARD_MIN_PRIOR,
  CHECKPOINT_SHRINK_GUARD_RATIO,
  CHECKPOINT_SHRINK_GUARD_ENABLED,
  ROOT_NODE_KEY_PREFIX,
  LEGACY_ROOT_NODE_KEY,
  BUBBLE_TEXT_WIDTH_RATIO,
  BUBBLE_TEXT_REF_SIZE,
  LAYOUT_CENTER_X,
  LAYOUT_CENTER_Y,
  PHYSICS_MAGNET_GAP,
  PHYSICS_REPULSION_STRENGTH,
  PHYSICS_REPULSION_RANGE,
  PHYSICS_DAMPING,
  PHYSICS_MAX_VELOCITY,
  PHYSICS_JITTER,
  PHYSICS_FPS,
  PHYSICS_SLEEP_THRESHOLD,
  PHYSICS_SLEEP_FRAMES,
  MODEL_CONTEXT_LIMITS,
  DEFAULT_CONTEXT_LIMIT,
  MODEL_PRICING,
  DEFAULT_PRICING,
  calculateTokenCost,
  MODEL_FAMILY_DEFAULTS,
  isKnownFamily,
  MODEL_SEED_ENTRIES,
  parseFamilyFromFullId,
  parseModelSemver,
  listModelFamilies,
  listEffortLevels,
  getModelPricing,
  getModelContextLimit,
  resolveAliasToLatest,
  TOKEN_BYTES_RATIO,
  TOKEN_SUBAGENT_FETCH_CONCURRENCY,
  SYSTEM_PROMPT_ESTIMATE,
  TOOL_SCHEMA_ESTIMATE,
  GIT_STATUS_ESTIMATE,
  TOKEN_FIXED_CATEGORIES,
  estimateTokens,
  CONTEXT_SOURCE_IDS,
  CONTEXT_SOURCE_ID_LIST,
  CONTEXT_PLUGIN_ID_PREFIX,
  CONTEXT_PREVIEW_MAX_CHARS,
  CONTEXT_SPAWN_SWITCHES,
  resolveContextEnabled,
  IFRAME_BUBBLE_HEIGHT,
  FRONTEND_SERVER_PATTERNS,
  LOOPBACK_SNIFF_URLS_PER_BASH,
  LOOPBACK_SNIFF_PROBE_TTL_MS,
  IFRAME_PROXY_PATH,
  IFRAME_LOG_SERVER_BUFFER_MAX,
  IFRAME_LOG_CLIENT_BUFFER_MAX,
  IFRAME_LOG_POLL_INTERVAL_MS,
  IFRAME_LOG_BATCH_MS,
  IFRAME_LOG_TAIL_BYTES,
  IFRAME_DEAD_GRACE_MS,
  SERVER_LOG_BUFFER_MAX,
  SERVER_LOG_CLIENT_BUFFER_MAX,
  SERVER_LOG_BATCH_MS,
  SERVER_LOG_RECENT_VIEW_LIMIT,
  PIPELINE_CHILD_CONFIGS,
  PIPELINE_TYPE_INFO,
  PIPELINE_PARENT_BUBBLE_ID,
  AVAILABLE_AGENT_MODELS,
  AVAILABLE_AGENT_MODEL_FULL_IDS,
  AVAILABLE_AGENT_MODEL_IDS,
  isOpusModel,
  supportsFastMode,
  isForwardSubagentTextEnabled,
  AVAILABLE_AGENT_TOOLS,
  BACKFILL_AGENT_TOOLS,
  AGENT_TOOLS_BACKFILL_GEN,
  CLI_BUILTIN_TOOLS,
  LEGACY_AGENT_TOOLS,  ASK_USER_QUESTION_TIMEOUT_MS,
  CLAUDE_VERSION_PROBE_TIMEOUT_MS,
  CLAUDE_INSTALL_SCAN_MAX,
  CLAUDE_SETUP_INSTALL_COMMAND_WIN,
  CLAUDE_SETUP_INSTALL_COMMAND_POSIX,
  CLAUDE_SETUP_DOCS_URL,
  CLAUDE_SETUP_INSTALL_TIMEOUT_MS,
  CLAUDE_SETUP_VERIFY_RETRY_INTERVAL_MS,
  CLAUDE_SETUP_VERIFY_RETRY_MAX,
  CLAUDE_SETUP_OUTPUT_MAX_CHARS,
  CLAUDE_SETUP_READY_HOLD_MS,
  CLAUDE_AUTO_UPDATE_BOOT_DELAY_MS,
  HOOK_TRANSPORT_REFRESH_DELAY_MS,  LOCKED_AGENT_TOOLS,
  AVAILABLE_PERMISSION_MODES,
  PERMISSION_MODES_WITHOUT_PROMPT,
  PERMISSION_MODE_CLI_VALUES,
  toCliPermissionMode,
  normalizeAgentDefinitionName,
  buildAgentsFlagJson,
  normalizePluginDirs,
  AVAILABLE_SETTING_SOURCES,
  AVAILABLE_AUTOCOMPACT_VALUES,
  DEFAULT_AUTOCOMPACT_TOKENS,
  resolveAutoCompact,
  AGENT_COMPACT_COMMAND,
  buildAgentSelfCompactRule,
  DEFAULT_AGENT_CONFIG,
  AGENT_MEMORY_SCOPES,
  normalizeAgentMemoryScope,
  SUBAGENT_DEPTH_MIN,
  SUBAGENT_DEPTH_MAX,
  normalizeSubagentDepth,
  BASH_TIMEOUT_MS_MIN,
  BASH_TIMEOUT_MS_MAX,
  BASH_DEFAULT_TIMEOUT_MS_CLI_DEFAULT,
  BASH_MAX_TIMEOUT_MS_CLI_DEFAULT,
  normalizeBashTimeoutMs,
  AVAILABLE_ISOLATION_MODES,
  AVAILABLE_EFFORT_LEVELS,
  parseModelFamily,
  TASK_EDGE_TEMPLATES,
  TASK_EDGE_STYLES,
  TASK_EDGE_KIND_STYLES,
  TASK_EDGE_DEFAULTS,
  TASK_EDGE_DISPATCH_DEFAULT_TIMEOUT_MS,
  TASK_EDGE_CRITIQUE_MAX_REWORK_LIMIT,
  AUTO_AGENT_RUN_MAX_PER_AGENT,
  AUTO_AGENT_RUN_DEFAULT_REWORK_BUDGET,
  VERIFICATION_VERDICT_SCHEMA_GUIDE,
  TASK_EDGE_AUTO_REWORK_COMMAND_LABEL,
  GIT_STATUS_CONFIG,
  COMMENT_BOX_DEFAULTS,
  COMMENT_BOX_LOD,
  CANVAS_LOD,
  COMMENT_BOX_PALETTE,
  SESSION_MEMO,
  SESSION_MEMO_PALETTE,
  SESSION_MEMO_DEFAULT_COLOR,
  CAPTURE_BUBBLE_DEFAULTS,
  CAPTURE_SNAP,
  CAPTURE_PLAYTEST,
  SUPPORTED_UI_LOCALES,
  LOCALE_META,
  DEFAULT_UI_LOCALE,
  AVAILABLE_CUSTOM_MODES,
  AVAILABLE_EXECUTION_MODES,
  CMD_CLI_KINDS,
  resolveCmdCliKind,
  TERMINAL_SCROLLBACK_LINES,
  TERMINAL_SCROLLBACK_MIN,
  TERMINAL_SCROLLBACK_MAX,
  TERMINAL_SCROLLBACK_BYTES_PER_LINE,
  clampTerminalScrollback,
  TERMINAL_RESIZE_DEBOUNCE_MS,
  CMD_RESIZE_REPAINT_MS,
  isConsoleRepaintChunk,
  shouldBufferPtyChunk,
  CMD_PREFILL_DELAY_MS,
  CMD_PREFILL_MAX_DEFER_MS,
  cmdPrefillDelay,
  CMD_STATE_TICK_MS,
  CMD_BLOCKED_IDLE_MS,
  CMD_IDLE_MS,
  CMD_BLOCK_TAIL_LINES,
  CMD_BLOCK_REASON_MAX,
  CMD_BLOCK_PATTERNS,
  CMD_PROCESS_POLL_MS,
  CMD_WAIT_MAX_MS,
  CMD_WAIT_POLL_MS,
  CMD_READ_MAX_LINES,
  CMD_SEND_MAX_CHARS,
  CMD_PANE_RATIO_MIN,
  CMD_PANE_RATIO_MAX,
  CMD_PANE_MAX,
  CMD_PANE_SEPARATOR,
  sanitizeCmdPaneTree,
  sanitizeSessionMemo,
  sanitizeSessionMemos,
  collectCmdPaneIds,
  cmdPaneTermId,
  splitCmdPane,
  closeCmdPane,
  resizeCmdPane,
  CMD_AGENT_COLOR,
  CONTI_DEFAULTS,
  CONTI_AGENT_RULES,
  STAMP_CATALOG,
  // §5.13 (Q) 대본 → 콘티 → 렌더
  STORYBOARD_PRESETS,
  STORYBOARD_PRESET_IDS,
  DEFAULT_STORYBOARD_PRESET_ID,
  resolveStoryboardPreset,
  normalizeStoryboardPresetId,
  CONTI_SCRIPT_MAX_CHARS,
  CONTI_SCRIPT_EXCERPT_MAX,
  CONTI_SCRIPT_FRAME_MIN,
  CONTI_SCRIPT_FRAME_MAX,
  RULES_HISTORY_MAX,
  CANVAS_CLIPBOARD_STORAGE_KEY,
  CANVAS_CLIPBOARD_SCHEMA_VERSION,
  CANVAS_CLIPBOARD_DEFAULT_PASTE_OFFSET,
  DIAGNOSTIC_LOG_MAX,
  STREAM_EVENTS_MAX_PER_SESSION,
  STREAM_EVENTS_TRIM_SLACK,
  STREAM_EVENTS_MAX_PER_INACTIVE_SESSION,
  STREAM_INACTIVE_SESSIONS_MAX,
  UPDATE_CHECK_INTERVAL_MS,
  AUTO_AGENT_LAYOUT_RADIUS,
  AUTO_AGENT_MAX_CLARIFYING_QUESTIONS,
  AUTO_AGENT_ROLE_POLICY,
  AUTO_AGENT_TEMPLATES,
  AUTO_AGENT_DEFAULT_RULES,
  AUTO_AGENT_BUILDER_CONFIG,
  AUTO_AGENT_BUILDER_INTERVIEW_TOOL,
  buildHarnessBuilderRules,
  AGENT_REPORT_MAX_PER_AGENT,
  AGENT_INTENT_FIRST_RULES,
  buildAgentCardCommonRules,
  CARD_RULES_DOCUMENT,
  buildAgentReportRules,
  AGENT_CARD_ENV_BASE,
  AGENT_CARD_ENV_TOKEN,
  AGENT_QUESTIONS_MAX_PER_AGENT,
  buildAgentQuestionRules,
  AGENT_REVIEWS_MAX_PER_AGENT,
  STREAM_DENSITIES,
  STREAM_DIFF_AUTO_EXPAND_MAX_LINES,
  DIFF_COMMENT_MAX,
  PREVIEW_PICK_SOURCE,
  PREVIEW_PICK_TEXT_MAX,
  PREVIEW_DEVICE_PRESETS,
  PREVIEW_SNIP_MIN_PX,
  resolveCompareWidths,
  STREAM_COMPACT_TEXT_CLAMP_LINES,
  STREAM_COMPACT_TEXT_CLAMP_CHARS,
  STREAM_COMPACT_LIST_PREVIEW,
  STREAM_COMPACT_SUMMARY_CHARS,
  buildAgentReviewRules,
  AGENT_LISTS_MAX_PER_AGENT,
  PLAY_BUBBLE_DEFAULT_WIDTH,
  PLAY_BUBBLE_DEFAULT_HEIGHT,
  PLAY_PREVIEW_DEFAULT_WIDTH,
  PLAY_PREVIEW_DEFAULT_HEIGHT,
  PLAY_PREVIEW_GAP,
  PLAY_START_TIMEOUT_MS,
  PLAY_PROBE_INTERVAL_MS,
  PLAY_ALIVE_SWEEP_MS,
  PLAY_STATIC_INDEX_FILES,
  PLAY_STATIC_ROOT_DIRS,
  buildPlayRecipeAskPrompt,
  SPEC_BUBBLE_DEFAULT_WIDTH,
  SPEC_BUBBLE_DEFAULT_HEIGHT,
  SPEC_TITLE_MAX,
  SPEC_ITEM_TEXT_MAX,
  SPEC_BODY_MAX,
  SPEC_MAX_ITEMS,
  SPEC_TASK_LABEL_MAX,
  REVIEW_DIFF_MAX_BYTES,
  REVIEW_FILES_MAX,
  REVIEW_REQUESTS_MAX_PER_PROJECT,
  REVIEW_DECISIONS_MAX,
  REVIEW_REASON_MAX,
  REVIEW_REJECT_FILES_MAX,
  SPEC_TASK_OFFSET_X,
  SPEC_TASK_GAP_Y,
  SPEC_RULES_BEGIN,
  SPEC_RULES_END,
  buildSpecTaskRules,
  LAB_BUBBLE_DEFAULT_WIDTH,
  LAB_BUBBLE_DEFAULT_HEIGHT,
  LAB_TITLE_MAX,
  LAB_VARIANT_LABEL_MAX,
  LAB_TASK_MAX,
  LAB_RULES_APPEND_MAX,
  LAB_SUMMARY_MAX,
  LAB_MAX_VARIANTS,
  LAB_RUNS_MAX_PER_PROJECT,
  LAB_WORKTREE_PREFIX,
  WORKTREE_REAP_SETTLE_MS,
  LAB_CARD_OFFSET_X,
  LAB_CARD_GAP_Y,
  LAB_RULES_BEGIN,
  LAB_RULES_END,
  buildLabVariantRules,
  estimateLabCostUsd,
  SHELF_BUBBLE_DEFAULT_WIDTH,
  SHELF_BUBBLE_DEFAULT_HEIGHT,
  SHELF_MAX_ITEMS,
  SHELF_BUBBLES_MAX_PER_PROJECT,
  SHELF_TITLE_MAX,
  SHELF_LABEL_MAX,
  SHELF_COMMAND_MAX,
  SHELF_PROMPT_MAX,
  SHELF_RUN_TIMEOUT_MS,
  SHELF_RUN_OUTPUT_MAX_CHARS,
  SHELF_EXPORT_VERSION,
  SHELF_CARD_OFFSET_X,
  SHELF_IMPORT_MAX_ITEMS,
  SHELF_ICONS,
  SHELF_DEFAULT_ICON,
  SHELF_ITEM_COLORS,
  SHELF_DEFAULT_ITEM_COLOR,
  normalizeShelfIcon,
  normalizeShelfColor,
  normalizeShelfImport,
  COST_MAP_SWEEP_INTERVAL_MS,
  COST_MAP_ACTIVE_WINDOW_MS,
  COST_MAP_SESSIONS_MAX,
  COST_MAP_AGENTS_MAX,
  COST_MAP_DAYS_MAX,
  COST_WARN_USD,
  COST_DANGER_USD,
  COST_PERIODS,
  emptyCostTotals,
  addCostTotals,
  costTokenTotal,
  hasCostActivity,
  costDayKey,
  costPeriodStart,
  isCostDayInPeriod,
  sumCostDays,
  buildCostPeriodTotals,
  costTone,
  formatCostUsd,
  formatTokenCount,
  // §5.22 — 권한·감사 경계(판정은 서버·클라 공용 순수 함수 한 곳).
  AUDIT_RISK_KINDS,
  AUDIT_ENTRIES_MAX_PER_PROJECT,
  AUDIT_SUMMARY_MAX_CHARS,
  AUDIT_TARGET_MAX_CHARS,
  AUDIT_REASON_MAX_CHARS,
  AUDIT_TIMELINE_PAGE_SIZE,
  AUDIT_SNAPSHOT_ENTRIES,
  AUDIT_WRITE_TOOLS,
  AUDIT_NETWORK_TOOLS,
  AUDIT_DELETE_PATTERNS,
  AUDIT_NETWORK_PATTERNS,
  AUDIT_CONFIG_PATH_PATTERNS,
  AUDIT_CONFIG_MUTATION_PATTERNS,
  AUDIT_URL_PATTERN,
  AUDIT_LOOPBACK_HOSTS,
  AUDIT_PATH_INPUT_TOOLS,
  AUDIT_PATH_INPUT_KEYS,
  AUDIT_ABSOLUTE_PATH_PATTERNS,
  AUDIT_HOME_PREFIX_PATTERN,
  AUDIT_MSYS_PATH_PATTERN,
  AUDIT_RELATIVE_ESCAPE_PATTERN,
  AUDIT_OUTSIDE_IGNORE_PATTERNS,
  AUDIT_TOKEN_WRAPPER_PATTERNS,
  AUDIT_TOKEN_FLAG_VALUE_PATTERN,
  AUDIT_FALLBACK_PATH_PLATFORM,
  DEFAULT_AUDIT_BOUNDARY,
  isAuditLoopbackTarget,
  isAuditPathOutside,
  classifyToolRisk,
  summarizeToolCall,
  isAuditRiskEnabled,
  shouldEscalateRisk,
  normalizeAuditBoundary,
  isDefaultAuditBoundary,
  emptyAuditCounts,
  AGENT_FEEDBACK_MAX_PER_AGENT,
  AGENT_FEEDBACK_DIGEST_MAX,
  AGENT_FEEDBACK_DISTILL_MAX,
  AGENT_FEEDBACK_SUMMARY_ITEM_MAX,
  buildAgentFeedbackBlock,
  COMMAND_DISPATCH_MODES,
  DEFAULT_COMMAND_DISPATCH_MODE,
  COMMAND_MERGE_SEPARATOR,
  normalizeCommandDispatchMode,
  // §5.5 #17-12 ③ — 실패 사유 코드 전량(화면이 문장을 고르는 기준. 클라가 자기 목록을 따로 두지 않는다).
  COMMAND_ERROR_CODES,
  COMMAND_ERROR_CODES_WITH_EXIT,
  // §5.5 #17-29 — 훅 버블 읽기 전용 경계(서버 REST 가드 · 클라 UI 가 같은 술어를 쓴다).
  isReadOnlyHookAgent,
  READ_ONLY_HOOK_AGENT_ERROR,
  SESSION_LOOP_MAX_ITERATIONS,
  SESSION_LOOP_DEFAULT_TOTAL,
  SESSION_LOOP_DEFAULT_INTERVAL_MS,
  SESSION_LOOP_MAX_INTERVAL_MS,
  SESSION_LOOP_COMMAND_MAX,
  VERIFICATION_RUNS_MAX_PER_SESSION,
  VERIFICATION_FOCUS_MAX,
  VERIFICATION_ATTEMPTS_MAX,
  VERIFICATION_REASON_MAX,
  VERIFICATION_ATTEMPT_TEXT_MAX,
  VERIFICATION_DEMO_MAX_PER_SESSION,
  VERIFICATION_DEMO_STEPS_MAX,
  VERIFICATION_DEMO_STEP_TEXT_MAX,
  VERIFICATION_DEMO_LABEL_MAX,
  VERIFICATION_DEMO_EXPECTED_MAX,
  VERIFICATION_DEMO_FRAMES_MAX,
  VERIFICATION_DEMO_DIR,
  VERIFY_SLASH_COMMAND,
  VERIFY_RECORDED_SKILL_PATH,
  SESSION_LOOP_COMPACT_COMMAND,
  SESSION_LOOP_CLEAR_COMMAND,
  SESSION_LOOP_PATH_MAX,
  SESSION_LOOP_MAX_COST_USD_LIMIT,
  SESSION_LOOP_MAX_DURATION_LIMIT_MS,
  SESSION_GOAL_TEXT_MAX,
  SESSION_GOAL_NOTE_MAX,
  SESSION_GOAL_HISTORY_MAX,
  SESSION_GOAL_STEPS_MAX,
  SESSION_GOAL_STEP_TEXT_MAX,
  buildSessionGoalRules,
  buildSessionGoalState,
  buildSessionGoalProtocol,
  VIBISUAL_CARD_SENTINEL,
  // §5.19 All Model — 로컬 LLM
  ALL_MODEL_INSTALL_ID,
  LOCAL_AGENT_COLOR,
  LLAMA_RELEASE_LATEST_API,
  LLAMA_RELEASES_LIST_API,
  LOCAL_ENGINE_DEFAULT_BACKENDS,
  LOCAL_MODEL_MAX_LOADED,
  LOCAL_MODEL_IDLE_UNLOAD_MS,
  LOCAL_ENGINE_PORT_BASE,
  LOCAL_ENGINE_BOOT_TIMEOUT_MS,
  HF_MODEL_API,
  LOCAL_MODEL_SEARCH_LIMIT,
  LOCAL_MODEL_FILE_LIMIT,
  LOCAL_MODEL_TOP_QUANT_COUNT,
  QUANT_POPULARITY,
  QUANT_RANK_UNKNOWN,
  quantRank,
  LOCAL_MODEL_CATALOG_SORTS,
  HF_SORT_FIELD,
  HF_EXPAND_FIELDS,
  LOCAL_ENGINE_DIR_NAME,
  LOCAL_MODEL_DIR_NAME,
  LOCAL_MODEL_OVERHEAD_RATIO,
  LOCAL_MODEL_OVERHEAD_BYTES,
  LOCAL_MODEL_RAM_USABLE_RATIO,
  classifyModelFit,
  LOCAL_DEFAULT_CONTEXT_SIZE,
  LOCAL_CONTEXT_MIN,
  LOCAL_CONTEXT_MAX,
  LOCAL_ANSWER_BUDGET_RATIO,
  LOCAL_ANSWER_BUDGET_MIN,
  localAnswerBudget,
  LOCAL_THINKING_BUDGET_RATIO,
  localThinkingBudget,
  LOCAL_MODEL_NON_CHAT_PIPELINE_TAGS,
  isChatCapablePipelineTag,
  LOCAL_TOOL_MAX_ROUNDS,
  LOCAL_TOOL_READ_MAX_BYTES,
  LOCAL_TOOL_RESULT_MAX_CHARS,
  LOCAL_ANSWER_BUDGET_RESERVE,
  LOCAL_TOOL_REPEAT_LIMIT,
  LOCAL_COMPACT_MAX_TOKENS,
  LOCAL_ENGINE_CACHE_REUSE,
  LOCAL_CHARS_PER_TOKEN,
  LOCAL_TOOL_RESULT_CONTEXT_RATIO,
  localToolResultBudget,
  LOCAL_HISTORY_CONTEXT_RATIO,
  localHistoryBudget,
  LOCAL_TOOL_LIST_MAX_ENTRIES,
  LOCAL_WEB_SEARCH_MAX_HITS,
  LOCAL_WEB_SEARCH_API_URL,
  LOCAL_WEB_SEARCH_TIMEOUT_MS,
  LOCAL_TOOL_COMMAND_TIMEOUT_MS,
  LOCAL_TOOL_DEFS,
  LOCAL_TOOL_NAMES,
  LOCAL_READ_ONLY_TOOLS,
  LOCAL_EDIT_TOOLS,
  LOCAL_HOST_TOOLS,
  normalizeTodoStatus,
  LOCAL_PLANNING_TOOLS,
  LOCAL_EXIT_PLAN_TOOL,
  LOCAL_NETWORK_TOOLS,
  resolveLocalToolGate,
  normalizeAgentProvider,
  ALL_MODEL_DEFAULT_LABEL_RE,
  buildCmdCardProtocolRules,
  MOBILE_PAIR_CODE_LENGTH,
  MOBILE_PAIR_MAX_ATTEMPTS,
  MOBILE_SESSION_MAX,
  MOBILE_SESSION_COOKIE,
  MOBILE_EXTERNAL_PAIR_CODE_LENGTH,
  MOBILE_PAIR_BAN_MS,
  MOBILE_UPNP_LEASE_S,
  MOBILE_QR_TICKET_TTL_MS,
  MOBILE_QR_TOKEN_BYTES,
  MOBILE_QR_PATH,
  MOBILE_QR_PARAM,
  CHAT_PAIR_TICKET_TTL_MS,
  CHAT_PAIR_TOKEN_BYTES,
  CHAT_PAIR_MAX_ATTEMPTS,
  CHAT_PAIR_BAN_MS,
  CHAT_PEER_MAX,
  CHAT_UNPAIRED_NOTICE_MS,
  CHAT_PENDING_ACTION_MAX,
  CHAT_LOG_AGENT_MAX,
  CHAT_PAIR_ATTEMPT_MAX,
  CHAT_TELEGRAM_API_BASE,
  CHAT_TELEGRAM_POLL_S,
  CHAT_TELEGRAM_MESSAGE_MAX,
  CHAT_DISCORD_API_BASE,
  CHAT_DISCORD_INTENTS,
  CHAT_DISCORD_HEARTBEAT_MISS_MAX,
  CHAT_DISCORD_ZOMBIE_CLOSE_CODE,
  CHAT_DISCORD_MESSAGE_MAX,
  CHAT_DISCORD_PAIR_COMMAND,
  CHAT_RECONNECT_MIN_MS,
  CHAT_RECONNECT_MAX_MS,
  CHAT_ACTION_TTL_MS,
  CHAT_LOG_DEFAULT_LINES,
  CHAT_LOG_MAX_LINES,
  CHAT_LOG_BUFFER_LINES,
  CHAT_BRIDGE_FILE,
  DEFAULT_CHAT_VERBOSITY,
  BRAIN_SESSION_CANDIDATE_MAX,
  BRAIN_INJECTION_TOP_K,
  BRAIN_ALWAYS_RULE_MAX,
  BRAIN_TOPICS,
  BRAIN_CANONICAL_TYPES,
  BRAIN_EXPERIENCE_TYPES,
  BRAIN_CANONICAL_AREAS,
  BRAIN_AUTHORITY_RANK,
  BRAIN_AUTHORITY_VERIFIABLE_MIN,
  BRAIN_POLICY_TYPES,
  BRAIN_OBSERVATION_KEEP,
  BRAIN_SCOPE_AXES,
  BRAIN_KEY_SUBJECT_FILE_PATTERN,
  BRAIN_SCOPE_SPLIT_PATTERN,
  BRAIN_MIGRATION_LIST_MAX,
  BRAIN_MIGRATION_DUP_TITLE_MIN,
  BRAIN_TOPIC_MISC,
  BRAIN_TOPIC_MISC_TITLE,
  BRAIN_TOPIC_MISC_WHEN_TO_READ,
  BRAIN_STALE_THRESHOLD_MS,
  BRAIN_INJECTION_TOKEN_BUDGET,
  BRAIN_INJECTIONS_MAX_PER_AGENT,
  BRAIN_REFLECTION_MIN_EVENTS,
  BRAIN_REFLECTION_DEBOUNCE_MS,
  BRAIN_REFLECTION_MAX_PER_HOUR,
  BRAIN_REFLECTION_MAX_CONCURRENT,
  BRAIN_REFLECTION_CWD_DIRNAME,
  COMPLETION_CHIME_DEDUPE_MS,
  BRAIN_REFLECTION_MIN_NEW_LINES,
  BRAIN_REFLECTION_EMPTY_STREAK_THRESHOLD,
  BRAIN_REFLECTION_BACKOFF_MAX_MS,
  BRAIN_REFLECTION_TEXT_MAX_CHARS,
  BRAIN_REFLECTION_TOOL_RESULT_MAX_CHARS,
  BRAIN_REFLECTION_SYSTEM_PROMPT,
  BRAIN_REFLECTION_DISALLOWED_TOOLS,
  BRAIN_REF_FLUSH_MS,
  BRAIN_FILE_WARN_ONCE_PER_SESSION,
  BRAIN_SEARCH_MAX_RESULTS,
  BRAIN_REFLECTION_INPUT_MAX_CHARS,
  BRAIN_DEDUP_JACCARD_THRESHOLD,
  BRAIN_FEED_SECTION_SIZE,
  BRAIN_RANK_W_RELEVANCE,
  BRAIN_RANK_W_HELPFUL,
  BRAIN_RANK_W_FRESHNESS,
  BRAIN_RANK_W_PINNED,
  BRAIN_HELPFUL_SMOOTH_ALPHA,
  BRAIN_HELPFUL_SMOOTH_BETA,
  BRAIN_FRESHNESS_HALF_LIFE_MS,
  BRAIN_DEMOTE_IMPRESSION_MIN,
  BRAIN_DEMOTE_FACTOR,
  BRAIN_RESURFACE_MIN_AGE_MS,
  BRAIN_CONTRADICT_JACCARD_MIN,
  BRAIN_SUPERSEDE_CANDIDATE_MAX,
  BRAIN_NEGATION_PATTERN,
  BRAIN_ANCHOR_SHA_LEN,
  BRAIN_ANCHOR_MAX_FILE_BYTES,
  BRAIN_STALE_REPORT_ARCHIVE_MIN,
  BRAIN_TOPIC_CARD_BUDGET,
  BRAIN_PROJECT_CARD_BUDGET,
  BRAIN_AGENT_CARD_BUDGET,
  BRAIN_TOPIC_DOC_CORE_N,
  BRAIN_ARCHIVE_DIRNAME,
  BRAIN_ARCHIVE_LIST_MAX,
  BRAIN_REFLECTION_KNOWN_TITLE_MAX,
  BRAIN_DEMOTE_UNREFERENCED_MS,
  BRAIN_REFLECTION_PROMPT,
  buildBrainReflectionPrompt,
  buildBrainRulesSection,
  buildBrainSkillsSection,
  buildBrainNudgeSection,
  buildBrainTopicIndexSection,
  USAGE_LIMIT_WARN_PCT,
  USAGE_LIMIT_DANGER_PCT,
  CLAUDE_USAGE_POLL_INTERVAL_MS,
  CLAUDE_USAGE_PROBE_TIMEOUT_MS,
  CLAUDE_AUTH_PROBE_TIMEOUT_MS,
  CLAUDE_AUTH_LOGOUT_TIMEOUT_MS,
  CLAUDE_AUTH_POLL_INTERVAL_MS,
  CLAUDE_AUTH_LOGIN_POLL_INTERVAL_MS,
  CLAUDE_AUTH_LOGIN_TERM_ID,
  CLAUDE_AUTH_TERMINAL_REVEAL_MS,
  BUILTIN_SLASH_COMMANDS,
  slashCommandNeedsTerminal,
  PLUGIN_SUPPORTED_CONTRIBUTIONS,
  PLUGIN_ID_PATTERN,
  APP_API_PREFIX,
  PLUGIN_API_PREFIX,
  BRAIN_AXIS_IDS,
  DEFAULT_BRAIN_AXES,
  resolveBrainProjectKey,
  resolveBrainActivation,
  isBrainEnabled,
  isBrainAxisEnabled,
  shouldPromptBrainActivation,
  BRAIN_SKILLS_DIRNAME,
  BRAIN_SKILL_FILENAME,
  BRAIN_SKILL_INJECTION_TOP_K,
  BRAIN_SKILL_DESCRIPTION_MAX_CHARS,
  BRAIN_SKILL_BODY_MAX_CHARS,
  BRAIN_SKILL_BUDGET,
  BRAIN_SKILL_PROMOTE_MIN_LESSONS,
  BRAIN_SKILL_DRAFT_MIN_TOOL_CALLS,
  BRAIN_RECALL_MAX_RESULTS,
  BRAIN_RECALL_EXCERPT_CHARS,
  BRAIN_RECALL_SESSION_SCAN_MAX,
  BRAIN_BIGRAM_MIN_SCORE,
  BRAIN_NUDGE_MIN_INTERVAL_MS,
  BRAIN_NUDGE_MAX_PER_SESSION,
  BRAIN_GROUNDING_MAX_FILE_BYTES,
  BRAIN_GROUNDING_MIN_ANCHOR_HIT_RATIO,
  BRAIN_CURATOR_PAGE_SIZE,
  BRAIN_OPERATOR_CARD_BUDGET,
} from './constants.js';

// §5.3 #28 v1.60 — STAMP_CATALOG 메타 타입 (constants.ts 에 정의됨)
export type { StampSpec } from './constants.js';
/** §5.17 (A) — `compare` 가 나란히 놓는 폭 한 칸. */
export type { PreviewCompareWidth } from './constants.js';
/** §5.20 — 선반 가져오기 판정 결과(클라·서버 공용 순수 함수의 반환형). */
export type { ShelfImportDraftItem, ShelfImportResult } from './constants.js';

/** §5.21 — 금액 색조(배지·표 공용). */
export type { CostTone } from './constants.js';

// §5.22 — `outside` 판정에 넘기는 경계(프로젝트 루트·세션 cwd·플랫폼).
export type { AuditRiskOptions } from './constants.js';
// §5.13 (R) — 파일 하나를 무엇으로 여는가(클릭 지점 전부가 같은 판정을 쓴다).
export type { WorkspaceOpenAction, WorkspaceOpenAppClaim, WorkspaceOpenPlan, MediaConvertKind } from './constants.js';
export type { MediaToolsInfo, MediaConvertJob, MediaConvertStatus } from './types.js';

// §9 v3.89 — graph_snapshot 키맵 슬라이스 증분 (서버 인코딩 / 클라 복원 공용)
export { diffKeyedSlice, applyKeyedSliceDelta } from './keyedSliceDelta.js';

// §3.2.4 F축 — 바이트 예산 LRU 캐시.
export { ByteBudgetCache, approximateStringBytes, capMapSize } from './byteBudgetCache.js';
export type {
  ByteBudgetCacheOptions,
  ByteBudgetCacheStats,
  EvictableCache,
  SizeOf,
} from './byteBudgetCache.js';

// §3.2.4 H·I축 — 힙 계측 · 압력 대응 진단.
export type {
  MemorySample,
  MemoryPressureLevel,
  MemoryCacheStat,
  MemoryDiagnosticsReport,
} from './types.js';

// §5.5 v4.92 — 스트림 복원 예산 판정 (서버 저장 제외 / 클라 표시 필터 공용)
export {
  parseSystemSubtype,
  isNeverRenderedStreamEvent,
  THINKING_PULSE_SUBTYPE,
  HIDDEN_SYSTEM_SUBTYPES,
  isHiddenSystemSubtype,
  isNeverRenderedSystemSubtype,
  // §5.5 #17-13 ⑤-3 v5.08 — 작업 칩 payload (서버 발신 / 클라 합치기 공용)
  formatSystemChip,
  parseSystemTaskInfo,
  foldTaskBookend,
  SYSTEM_CHIP_TEXT_MAX,
  TASK_CHIP_START_SUBTYPE,
  TASK_CHIP_END_SUBTYPE,
  // §4 (CLI 사양 추종) — `--include-hook-events` 훅 줄 subtype
  HOOK_STREAM_SUBTYPES,
  isHookStreamSubtype,
} from './streamNoise.js';
export type { StreamNoiseProbe, StreamTaskInfo, StreamTaskStatus } from './streamNoise.js';

// §5.5 #17-20 v4.74 — 디버그·실행 런처 (A 실행 구성 / B MCP 프리셋 / C 외부 디버거)
export type {
  RunConfigSource,
  RunRuntime,
  RunConfigKind,
  RunConfig,
  RunConfigScanResult,
  McpPresetCategory,
  McpServerPreset,
  ExternalDebuggerId,
  ExternalDebuggerInfo,
} from './types.js';

// §5.5 #17-31 — 이 프로젝트에서 쓸 수 있는 MCP 인벤토리(글로벌·로컬·프로젝트·프리셋)
export type {
  McpServerScope,
  McpServerState,
  McpServerTransport,
  McpRequirementKind,
  McpRequirement,
  McpServerEntry,
  McpInventory,
} from './types.js';

// §5.5 #17-32 — 이 세션에 적용되는 Claude Code 훅 인벤토리(글로벌·프로젝트·로컬·정책)
export type {
  HookScope,
  HookLockReason,
  HookEntry,
  HookInventory,
  HookFiredPayload,
} from './types.js';
export { hookMatcherMatches, isWildcardHookMatcher } from './hookMatcher.js';

// §5.5 #17-33 — Claude Code 자신의 플러그인 체계(글로벌·이 프로젝트·마켓플레이스)
export type {
  ClaudePluginScope,
  ClaudePluginPlacement,
  ClaudePluginEntry,
  ClaudeMarketPlugin,
  ClaudeMarketplaceEntry,
  ClaudePluginInventory,
} from './types.js';
export { resolvePluginPlacement, splitPluginId, normalizePluginPath, placementAppliesHere } from './claudePlugin.js';
export type { DebugLaunchRecipe } from './constants.js';
export {
  RUN_CONFIG_MAX,
  RUN_FAILURE_TAIL_LINES,
  RUN_OUTPUT_BUFFER_LINES,
  RUN_OUTPUT_FLUSH_MS,
  DEBUG_PORT_BASE,
  DEBUG_PORT_SCAN_MAX,
  DEBUG_LAUNCH_RECIPES,
  MCP_SERVER_PRESETS,
  detectRunRuntime,
  buildDebugCommand,
  findMcpPreset,
} from './constants.js';

// §5.5 #17-20 ⑩⑪ v4.94 — 공통 디버그 층(런타임 무관) + 출력 문제 매처
export type {
  DebugBackendKind,
  DebugAdapterTransport,
  DebugAttachKind,
  DebugAdapterSpec,
  DebugSessionStatus,
  DebugStoppedReason,
  DebugBreakpoint,
  DebugStackFrame,
  DebugVariable,
  DebugScope,
  DebugSessionState,
  DebugEventPayload,
  ProblemSeverity,
  ProblemMatch,
} from './types.js';
export type { ProblemMatcher } from './constants.js';
export {
  DEBUG_ADAPTER_PORT_TOKEN,
  DEBUG_ADAPTER_PORT_BASE,
  DEBUG_ADAPTER_READY_TIMEOUT_MS,
  DEBUG_REQUEST_TIMEOUT_MS,
  DEBUG_ADAPTERS,
  PROBLEM_MATCHERS,
  findDebugAdapter,
  matchProblemLine,
} from './constants.js';
export type { SessionRunState, SessionRunInputs, AgentBadgeShareInputs } from './sessionRunState.js';
export {
  EMPTY_SESSION_RUN_INPUTS,
  isSessionRunning,
  hasSessionWork,
  resolveSessionRunState,
  agentBadgeShare,
} from './sessionRunState.js';

// 경로 대소문자 정책 SSOT — Linux 는 대소문자를 구분하므로 무조건 소문자로 접으면 안 된다.
// shared 는 브라우저에서도 로드되므로 플랫폼은 인자로 받는다(pathCase.ts 머리말 참조).
export type { PlatformName } from './pathCase.js';

// §4 — 업데이트 전달 방식 판정(무서명 macOS 는 self-install). 플랫폼은 인자로 받는다.
export type { UpdateDeliveryInput } from './updateDelivery.js';
// §4 self-install — 받은 번들이 정말 이 아키텍처의 것인가. 파일 이름·피드를 믿지 않고
// Mach-O 헤더를 직접 읽는다. 아키텍처도 인자로 받는다(실기 없이 세 경우를 다 재기 위해).
export type { ProcessArch, MachoArch } from './machoArch.js';
export {
  MACHO_HEADER_PROBE_BYTES,
  readMachoArchs,
  isArchCompatible,
  toProcessArch,
} from './machoArch.js';
export {
  RELEASES_PAGE_BASE,
  resolveUpdateDelivery,
  releasesPageUrl,
  readUpdateDelivery,
  RELEASES_DOWNLOAD_BASE,
  macUpdateAssetName,
  macUpdateAssetUrl,
} from './updateDelivery.js';
// §3.7 — 바깥 브라우저 열기 실패 판정. 리눅스의 `shell.openExternal` 은 실패해도 resolve 하므로
// (xdg-open 을 wait=false 로 띄운다) 프라미스 대신 "열어 줄 프로그램이 있는가"를 잰다. 폴백 ❌.
export type {
  ExternalOpenFailureReason,
  ExternalOpenFailure,
  LinuxBrowserProbe,
  ExternalOpenNoticeInput,
} from './externalOpen.js';
export {
  LINUX_BROWSER_BINARIES,
  needsBrowserProbe,
  hasLinuxBrowserHandler,
  resolveExternalOpenNotice,
} from './externalOpen.js';
export {
  isCaseInsensitiveFs,
  isPathWithin,
  normalizePathShape,
  pathKey,
  legacyLowerPathKey,
  lookupByPath,
  samePath,
} from './pathCase.js';

// §4 — 개별 에이전트 설정이 설정 창의 전역 기본값과 어디서 갈라지는지. "미설정"의 표기가 필드마다
// 달라서(effort:'default' · isolation:'none' · maxTurns:0 · forwardSubagentText:undefined=켬)
// 접힘 규칙을 화면이 아니라 한 곳에 둔다.
export type { AgentConfigComparedField } from './agentConfigDiff.js';
export {
  AGENT_CONFIG_IDENTITY_FIELDS,
  AGENT_CONFIG_COMPARED_FIELDS,
  AGENT_MAX_TURNS_UI_FALLBACK,
  resolveAgentDefaults,
  normalizeAgentFieldForCompare,
  agentFieldDiffers,
  diffAgentConfigFromDefaults,
} from './agentConfigDiff.js';

// §5.5 #17-6 (H-4) — 끌고 다니는 창의 "앱 안/밖" 판정. 창을 움직이는 쪽(Electron main)과
// 규칙이 갈라지지 않게 순수 함수 한 곳에 둔다(화면 API ❌ — 숫자만 본다).
export type { ScreenRect, AppEntryStep } from './windowDragRegion.js';
export {
  DETACHED_REDOCK_INSET_PX,
  isCursorDeepInside,
  isCursorOutsideRect,
  stepAppEntry,
} from './windowDragRegion.js';

// §5.5 #17-27 ⑮ — HTML 을 페이지로 여는 **경로형** 창구의 규약. 조립(클라 iframe src)과
// 해석(서버 라우트)이 갈라지면 화면에는 흰 사각형만 남으므로 한 파일에 둔다.
export type { WorkspaceSiteRequest, WorkspaceSiteInspectHit } from './workspaceSite.js';
export {
  WORKSPACE_SITE_PATH,
  WORKSPACE_HTML_EXTENSIONS,
  WORKSPACE_SITE_MIME_BY_EXT,
  WORKSPACE_SITE_REWRITE_MAX_BYTES,
  isWorkspaceHtmlPath,
  workspaceSiteMime,
  workspaceSiteBase,
  workspaceSiteUrl,
  parseWorkspaceSitePath,
  rewriteWorkspaceSiteHtml,
  rewriteWorkspaceSiteCss,
  workspaceSiteRewriteKind,
  WORKSPACE_SITE_REPORT_MESSAGE,
  workspaceSiteReporterScript,
  injectWorkspaceSiteAgents,
  WORKSPACE_SITE_SOURCE_ATTR,
  WORKSPACE_SITE_INSPECT_REQUEST,
  WORKSPACE_SITE_INSPECT_RESULT,
  annotateWorkspaceSiteSource,
  workspaceSiteInspectorScript,
} from './workspaceSite.js';

// §5.5 #17-19 ⑦ — 탐색기가 만들거나 바꿔 다는 **이름**의 판정. 입력창(클라)과 디스크(서버)가
// 같은 규칙 하나를 봐야 "화면은 받아 줬는데 서버가 거절"이 생기지 않는다.
export type { WorkspaceEntryNameError } from './workspaceEntryName.js';
export {
  WORKSPACE_ENTRY_NAME_MAX,
  workspaceEntryNameError,
} from './workspaceEntryName.js';

// §7.11 — 루프백 주소 판정·별칭. 감지 폴백(서버)과 "눌러서 프리뷰"(클라)가 같은 규칙을 쓴다.
export {
  LOOPBACK_HOST_ALIASES,
  isLoopbackHostname,
  parseLoopbackUrl,
  isLoopbackPreviewUrl,
  loopbackUrlVariants,
  extractLoopbackUrls,
} from './loopbackUrl.js';

// §4 (첫 실행 온보딩) — ①설치 → ②로그인 → ③프로젝트 폴더. 세 게이트와 생성 REST 가 같은
// 순서 판정 하나를 봐야 "화면은 막았는데 서버는 만들어 준다"가 생기지 않는다.
export type { OnboardingStep, OnboardingInput } from './onboarding.js';
export {
  NO_PROJECT_FOLDER_ERROR,
  resolveOnboardingStep,
  isNoProjectFolderError,
} from './onboarding.js';
