export type {
  UiLocale,
  HookEventPayload,
  NodeStatus,
  ToolDurationEntry,
  DiagnosticEntry,
  CompactCount,
  RateLimitInfo,
  ClaudeUsageLimit,
  ClaudeUsageExtraCredits,
  ClaudeUsageSource,
  ClaudeUsageError,
  ClaudeUsageInfo,
  ClaudeAuthStatus,
  ClaudeAuthProbeError,
  ClaudeAuthLoginMode,
  UsageCollectorStatus,
  BubbleType,
  TidyBand,
  TidySort,
  TidyGeometry,
  CaptureSourceKind,
  CaptureSourceInfo,
  AppBubble,
  CaptureBubble,
  PlayRecipeKind,
  PlayRecipeSource,
  PlayBubbleStatus,
  PlayRecipe,
  PlayRecipeCandidate,
  PlayBubble,
  SpecItem,
  SpecDoc,
  ReviewFileChangeType,
  ReviewFileChange,
  ReviewDecisionKind,
  ReviewDecision,
  ReviewRequestStatus,
  ReviewRequest,
  LabVariantConfig,
  LabResultStatus,
  LabResult,
  LabVariant,
  LabRunStatus,
  LabRun,
  ShelfItemKind,
  ShelfRunStatus,
  ShelfIconName,
  ShelfItemRun,
  ShelfItem,
  ShelfBubble,
  ShelfExportItem,
  ShelfExport,
  CostTotals,
  CostPeriod,
  CostPeriodTotals,
  CostDayBucket,
  CostSessionEntry,
  CostAgentTotal,
  ProjectCostMap,
  AuditRiskKind,
  AuditDecisionSource,
  AuditEntry,
  AuditBoundaryConfig,
  AuditRetired,
  AuditCounts,
  ProjectAuditLog,
  CompactWorkingSet,
  CompactNotCarried,
  CompactOutcome,
  CompactFailReason,
  CompactMarker,
  PreimageSkipReason,
  FilePreimage,
  InsuranceRetired,
  CompactWatchLevel,
  CompactWatchState,
  ResurrectableSession,
  InsuranceCounts,
  InsuranceSessionCounts,
  ProjectInsuranceLedger,
  CaptureMouseInput,
  CaptureKeyInput,
  CaptureInputEvent,
  CaptureTargetRect,
  CaptureInjectResult,
  BubbleStyleConfig,
  EdgeStyleConfig,
  BubbleData,
  ActivityEdge,
  AgentStatus,
  WSMessageType,
  WSMessage,
  PermissionRequest,
  PermissionDecision,
  AskUserQuestionRequest,
  AskUserQuestionDecision,
  AskUserQuestionAnswer,
  AskUserQuestionOption,
  AskUserQuestionItem,
  AskUserQuestionToolInput,
  AgentReport,
  AgentQuestionItem,
  AgentQuestions,
  AgentReview,
  AgentList,
  AgentFeedbackVerdict,
  AgentFeedbackTargetType,
  AgentFeedback,
  GraphSnapshot,
  GraphSnapshotWire,
  GraphSnapshotDeltas,
  KeyedSliceDelta,
  Result,
  BashEntry,
  FileEdit,
  // §5.23 도메인 버블
  WebEntry,
  WebEntryKind,
  ServerEntry,
  AgentEvent,
  TodoItem,
  StreamDensity,
  QueuedCommand,
  CommandDispatchMode,
  CommandErrorCode,
  CommandError,
  SessionLoop,
  SessionLoopMode,
  SessionLoopStatus,
  SessionLoopContextMode,
  VerificationRun,
  VerificationRunStatus,
  VerificationRecipeSource,
  VerificationAttemptRecord,
  VerifyVerdict,
  VerificationDemo,
  VerificationDemoStep,
  VerificationDemoFrame,
  SessionGoal,
  SessionGoalStatus,
  SessionGoalStep,
  SessionGoalStepStatus,
  VisualKindCard,
  VisualKindStatus,
  VisualKindSurface,
  GoalActionCard,
  GoalActionSource,
  SessionGoalProgress,
  SessionGoalProgressSource,
  ContextSourceCategory,
  ContextSourceControl,
  ContextSourceChild,
  ContextSourceItem,
  ContextInventory,
  ContextOverrideMap,
  ContextOverrides,
  ContextScopeLevel,
  ContextSourcePreview,
  SubAgent,
  SubAgentStatus,
  SessionMemo,
  SubAgentHistoryItem,
  RunningSubagentTask,
  FinishedSubagentTask,
  AgentPhase,
  ProjectInfo,
  EdgeSnapshot,
  ProjectMeta,
  FolderFileEntry,
  FolderFilePage,
  WorkspaceEntry,
  WorkspaceDirListing,
  WorkspacePathKind,
  WorkspacePathInfo,
  ExternalPathInfo,
  WorkspaceEol,
  WorkspaceFileContent,
  WorkspaceFileSaveRequest,
  WorkspaceFileSaveResult,
  WorkspaceImageSaveRequest,
  WorkspaceEntryCreateRequest,
  WorkspaceEntryRenameRequest,
  WorkspaceEntryMoveRequest,
  WorkspaceEntryDeleteRequest,
  WorkspaceEntryResult,
  WorkspaceEntryDeleteResult,
  ProjectCheckpoint,
  ProjectIdentity,
  GhostChangeType,
  GhostInfo,
  ServerKind,
  TurnTokenUsage,
  TokenCategoryEstimate,
  SessionTokenData,
  PipelineType,
  AgentRole,
  PipelineChildConfig,
  PipelineState,
  AgentConfig,
  AgentDefinition,
  ExecutionMode,
  CmdCliKind,
  CmdTerminalState,
  CmdTerminalSignal,
  CmdPaneLeaf,
  CmdPaneSplit,
  CmdPaneNode,
  ModelFamily,
  KnownModelFamily,
  ModelRegistry,
  ModelRegistryEntry,
  BuiltinSlashCommand,
  UserDefaults,
  UserDefaultsPatch,
  AgentConfigPatch,
  UserNotificationDefaults,
  UserAdvancedDefaults,
  PluginContributionKind,
  PluginCategory,
  PluginManifest,
  PluginFactMap,
  // §5.11 정독 게이트 · §5.5 #17-44
  SpecGateStrength,
  SpecUnitStatus,
  SpecUnit,
  SpecIndex,
  SpecReadSpan,
  SpecCitation,
  SpecRequiredEntry,
  SpecTrust,
  SpecGateEvent,
  SpecReadingState,
  SpecReadingRoute,
  SpecReadingSettings,
  SpecReadingScope,
  AutoGoalScope,
  AutoGoalSource,
  AutoGoalCandidate,
  AutoGoalSkillSummary,
  AutoGoalState,
  AutoGoalSummary,
  AutoGoalSettings,
  StreamEventType,
  SubAgentStreamEvent,
  TaskEdgeStatus,
  TaskEdgeForwardMode,
  TaskEdgeKind,
  TaskEdgeMessageFormat,
  TaskEdgeReturnFormat,
  TaskEdgePriority,
  TaskEdgeCritiqueTiming,
  TaskEdgeCritiqueAuthority,
  TaskEdgeCommandMode,
  TaskEdge,
  TaskEdgeTemplate,
  SessionSource,
  SessionLifeStatus,
  GitStatus,
  GitCommit,
  GitWorktreeStatus,
  PreviewPickPayload,
  PreviewDevicePreset,
  PreviewSnipRect,
  PageRegionCapture,
  ProjectMetaSnapshot,
  HydrateProjectPayload,
  ProjectHydratedPayload,
  UnloadProjectPayload,
  ProjectUnloadedPayload,
  SetProjectScopePayload,
  ProjectAgentCounts,
  IframeLogLevel,
  IframeLogLine,
  IframeLogSubscribePayload,
  IframeLogUnsubscribePayload,
  IframeLogInitPayload,
  IframeLogAppendPayload,
  ServerLogLevel,
  ServerLogCategory,
  ServerLogEntry,
  ServerLogSubscribePayload,
  ServerLogUnsubscribePayload,
  ServerLogInitPayload,
  ServerLogAppendPayload,
  AppState,
  AppStatePatch,
  ClosedTabEntry,
  IDEActivityBarPrefs,
  RetentionSettings,
  TokenSaverSettings,
  TokenSaverPreset,
  BackgroundTaskVerdict,
  SessionLivenessVerdict,
  SessionLivenessProbeResult,
  SessionLivenessProbeSettings,
  BackgroundTaskProbeResult,
  BackgroundTaskProbeSettings,
  RetentionLogEntry,
  StorageUsageKind,
  StorageUsageEntry,
  ProjectStorageUsage,
  WorktreeStorageUsage,
  StorageUsageReport,
  StorageCleanupResult,
  CommentBox,
  ContiCustomMode,
  AgentMemoryScope,
  ContiElementType,
  ContiElement,
  ContiFrame,
  ContiBadge,
  Conti,
  ContiEventPayload,
  ContiWorkSource,
  ActiveContiWork,
  ContiSource,
  ContiRenderLink,
  ContiRenderStatus,
  StoryboardPresetId,
  StoryboardPreset,
  RulesHistoryEntry,
  CanvasClipboardAgentEntry,
  CanvasClipboardTaskEdgeEntry,
  CanvasClipboardCommentBoxEntry,
  CanvasClipboardPayload,
  CanvasPasteResponse,
  ClaudeVersionInfo,
  ClaudeInstallProgress,
  // §5.19 All Model — 로컬 LLM
  AgentProviderKind,
  AgentProvider,
  // §5.25 Codex — 두 번째 엔진
  AgentEngineKind,
  EngineChoice,
  CodexAuthStatus,
  CodexAuthProbeError,
  CodexAuthLoginMode,
  CodexSetupPhase,
  CodexSetupState,
  CodexSetupProgress,
  CodexModelEntry,
  CodexModelCatalog,
  CodexHookState,
  CodexMcpServerEntry,
  CodexSkillEntry,
  CodexSkillSource,
  CodexPluginEntry,
  CodexHookEntry,
  CodexAgentsDocEntry,
  CodexInventory,
  CodexReviewMode,
  CodexReviewRun,
  LocalEngineBackend,
  LocalEngineProgress,
  LocalEngineState,
  LocalModelEntry,
  LocalModelDownloadProgress,
  LocalModelCatalogEntry,
  LocalDeviceInfo,
  LocalHardwareInfo,
  LocalModelFit,
  LocalModelCatalogRepo,
  LocalModelCatalogSort,
  LocalLlmState,
  ClaudeInstall,
  ClaudeInstallsInfo,
  ClaudeBinSource,
  ClaudeSetupPhase,
  ClaudeSetupState,
  ClaudeSetupProgress,
  AgentViewRosterEntry,
  AgentViewJobState,
  AutoAgentRole,
  AutoAgentTopology,
  AutoAgentComplexity,
  AutoAgentPhase,
  AutoAgentTemplate,
  AutoAgentClarifyingQuestion,
  AutoAgentSummary,
  AutoAgentRun,
  AutoAgentRunStatus,
  VerificationAttempt,
  VerificationKind,
  VerificationVerdict,
  EscalationReason,
  UpdatePhase,
  UpdateDelivery,
  UpdateState,
  UpdateErrorCode,
  MobileAccessState,
  MobileQrTicket,
  MobileExternalStatus,
  MobileExternalReason,
  ChatChannelKind,
  ChatVerbosity,
  ChatChannelStatus,
  ChatChannelError,
  ChatPeer,
  ChatPairTicket,
  ChatChannelState,
  ChatBridgeState,
  ChatCommandSession,
  ChatCommandTarget,
  ChatAction,
  ChatCard,
  TermCreateFrame,
  TermWriteFrame,
  TermResizeFrame,
  TermKillFrame,
  TermDataFrame,
  TermExitFrame,
  TermAckFrame,
  TermUnavailableFrame,
} from './types.js';

export type { ModelPricing, ModelPricingSource } from './constants.js';
/** §5.19 (H) — 로컬 도구 한 건의 처리 방식(allow/ask/deny). */
export type { LocalToolGate } from './constants.js';
// §5.3 #12-1 — 권한 축 동결 판정의 입·출력.
export type { AgentPermissionAxes, IngressPermissionGuardResult } from './constants.js';
export type { CompactAfterTurnInput } from './constants.js';
export type { NumericTokenSaverKey } from './constants.js';
/** §3.2.3 — 보존 설정 중 숫자 축만. 스위치 축은 min/max/step 이 뜻을 갖지 않는다. */
export type { NumericRetentionKey } from './constants.js';
// §5.5 #17-28 — 주입원 통제 3층(프로젝트/에이전트/세션) 판정에 쓰는 모양.
export type { ContextOverrideLayers, ContextScopeKeys } from './constants.js';

export {
  DEFAULT_PORT,
  WS_PATH,
  MAX_RECONNECT_ATTEMPTS,
  RECONNECT_BASE_DELAY,
  WS_BATCH_INTERVAL,
  WS_STREAM_BATCH_INTERVAL,
  WS_BATCH_INTERVAL_MAX,
  WS_BATCH_BACKOFF_FACTOR,
  CHECKPOINT_BATCH_INTERVAL,
  CHECKPOINT_BATCH_INTERVAL_MAX,
  CHECKPOINT_QUIET_SWEEP_MS,
  BUBBLE_STYLES,
  HOOK_AGENT_STYLE,
  BUBBLE_COLORS,
  READ_TOOLS,
  WRITE_TOOLS,
  EDGE_STYLE,
  NODE_MIN_SIZE,
  NODE_MAX_SIZE,
  FILE_MIN_SIZE,
  FILE_MAX_SIZE,
  HEAT_MIN_SIZE,
  HEAT_MAX_SIZE,
  HEATMAP_RAMP,
  HEATMAP_ZERO_COLOR,
  HEAT_CURVES,
  DEFAULT_HEAT_CURVE,
  HEAT_QUANTILE_BINS,
  HEAT_LEGEND_TICKS,
  MAX_BASH_HISTORY,
  MAX_FILE_EDITS,
  MAX_WRITE_DIFF_BYTES,
  BASH_WRITE_PENDING_MAX,
  FILE_EDIT_RETENTION_DAYS,
  MAX_FILE_EDIT_PATHS,
  FILE_EDIT_MERGE_WINDOW_MS,
  COMPLETED_COMMAND_MAX_PER_SESSION,
  SUB_STREAM_RETENTION_DAYS,
  ATTACHMENT_RETENTION_DAYS,
  TRASH_RETENTION_DAYS,
  RETENTION_LOG_MAX,
  RETENTION_DAY_MS,
  DEFAULT_RETENTION_SETTINGS,
  BG_TASK_QUIET_PROBE_MINUTES,
  BG_TASK_PROBE_TIMEOUT_MS,
  BG_TASK_PROBE_TAIL_BYTES,
  BG_TASK_PROBE_MAX_PATHS,
  BG_TASK_PROBE_GLOB_SCAN_MAX,
  BG_TASK_PROBE_REASON_MAX,
  BG_TASK_PROBE_MAX_PER_HOUR,
  BG_TASK_PROBE_CONCURRENCY,
  BG_TASK_PROBE_BACKOFF_FACTOR,
  BG_TASK_PROBE_BACKOFF_MAX,
  BG_TASK_PROBE_MODEL,
  DEFAULT_BG_TASK_PROBE_SETTINGS,
  BG_TASK_PROBE_LIMITS,
  BG_TASK_PROBE_MODELS,
  normalizeBgTaskProbeSettings,
  // §2.4 — 세션 생존 판정("실행중…"이 진짜인가). 구조·예산은 위 백그라운드 판정과 같은 계약.
  SESSION_PROBE_INTERVAL_MS,
  SESSION_PROBE_QUIET_MINUTES,
  SESSION_PROBE_TIMEOUT_MS,
  SESSION_PROBE_TAIL_BYTES,
  SESSION_PROBE_REASON_MAX,
  SESSION_PROBE_MAX_PER_HOUR,
  SESSION_PROBE_CONCURRENCY,
  SESSION_PROBE_BACKOFF_FACTOR,
  SESSION_PROBE_BACKOFF_MAX,
  SESSION_PROBE_MODEL,
  DEFAULT_SESSION_PROBE_SETTINGS,
  SESSION_PROBE_LIMITS,
  SESSION_PROBE_MODELS,
  normalizeSessionProbeSettings,
  RETENTION_LIMITS,
  normalizeRetentionSettings,
  isExpiredByDays,
  // §5.3 #9-1 토큰 절약 (토큰 축 J~P)
  TOKEN_SAVER_TURN_BUDGET_FLOOR,
  TOKEN_SAVER_OUTPUT_FLOOR,
  DEFAULT_TOKEN_SAVER_SETTINGS,
  TOKEN_SAVER_LIMITS,
  TOKEN_SAVER_PRESET_VALUES,
  detectTokenSaverPreset,
  normalizeTokenSaverSettings,
  resolveEffectiveAutoCompact,
  resolveTokenSaverNumber,
  buildTokenSaverEnv,
  // §5.26 컨텍스트 보험 — 보존 축(사용자 조절 가능)
  INSURANCE_RETENTION_DAYS,
  INSURANCE_VAULT_MAX_MB,
  INSURANCE_MARKERS_MAX_PER_PROJECT,
  INSURANCE_PREIMAGES_MAX_PER_PROJECT,
  // §3.2.4 런타임 메모리 자정작용
  SESSION_CACHE_BYTE_BUDGET,
  SESSION_CACHE_MAX_ENTRIES,
  JSONL_SCAN_CHUNK_BYTES,
  MEMORY_SAMPLE_INTERVAL_MS,
  MEMORY_SAMPLE_HISTORY,
  MEMORY_PRESSURE_HIGH_RATIO,
  MEMORY_PRESSURE_CRITICAL_RATIO,
  MEMORY_PRESSURE_EVICT_FRACTION,
  MEMORY_PRESSURE_COOLDOWN_MS,
  SESSION_KEYED_MAP_MAX,
  DEFAULT_MAX_SATELLITES,
  SATELLITE_MAX_BOUNDS,
  // §2.1 외부 폴더 표시 규약 — 요약 · 예산 · 접기 · 이름
  EXTERNAL_SUMMARY_CHIPS,
  EXTERNAL_TOP_BUDGET_DEFAULT,
  EXTERNAL_TOP_BUDGET_BOUNDS,
  EXTERNAL_PROMOTION_PER_PARENT,
  EXTERNAL_PROMOTION_HALF_LIFE_MS,
  EXTERNAL_FOLDER_MAX,
  EXTERNAL_PLACE_PATTERNS,
  // §7.5 폴더 목록 지연 로딩
  FOLDER_FILES_PAGE_SIZE,
  FOLDER_FILES_PAGE_MAX,
  // §5.23 도메인 버블 상한·표식
  DEFAULT_MAX_WEB_ENTRIES,
  WEB_ENTRY_MAX_BOUNDS,
  WEB_ENTRY_TEXT_MAX,
  WEB_ENTRY_RESULT_HOSTS_MAX,
  WEB_SEARCH_HOST,
  WEB_KEY_MARK,
  WEB_TOOLS,
  WORKSPACE_DIR_ENTRY_MAX,
  WORKSPACE_FILE_MAX_BYTES,
  IDE_EDITOR_MAX_TABS,
  IDE_EDITOR_TAB_SCOPE_MAX,
  IDE_EDITOR_WIDTH,
  WORKSPACE_IMAGE_EXTENSIONS,
  WORKSPACE_IMAGE_BAKEABLE_EXTENSIONS,
  WORKSPACE_IMAGE_MAX_BYTES,
  WORKSPACE_IMAGE_MIME_BY_EXT,
  WORKSPACE_PDF_EXTENSIONS,
  WORKSPACE_EXTERNAL_EXTENSIONS,
  WORKSPACE_CONVERT_VIDEO_EXTENSIONS,
  WORKSPACE_CONVERT_AUDIO_EXTENSIONS,
  MEDIA_CACHE_DIR,
  mediaCacheRelPath,
  WORKSPACE_MEDIA_MIME_BY_EXT,
  WORKSPACE_MEDIA_MAX_BYTES,
  workspaceMediaMime,
  resolveWorkspaceOpen,
  workspaceFileExt,
  isWorkspaceImagePath,
  isWorkspaceImageBakeable,
  workspaceImageMime,
  MAX_AGENTS,
  MAX_AGENT_EVENTS,
  CUSTOM_AGENT_MAX_PER_PROJECT,
  COMMAND_QUEUE_MAX_PER_SESSION,
  INITIAL_AGENT_COUNT,
  BUBBLE_TTL,
  AGENT_FADE_DURATION,
  SESSION_SCAN_INTERVAL,
  COWORK_HOME_CACHE_MS,
  COWORK_HOME_SCAN_MAX,
  AGENT_IDLE_THRESHOLD_MS,
  SUBAGENT_DORMANT_IDLE_MS,
  AGENT_IDLE_SWEEP_INTERVAL_MS,
  PROJECT_IDLE_UNLOAD_MS,
  PROJECT_IDLE_UNLOAD_SWEEP_MS,
  PROJECT_IDLE_UNLOAD_PRESSURE_MS,
  PROJECT_LOAD_HINT_DELAY_MS,
  PROJECT_LOAD_HINT_SLOW_MS,
  INTERRUPT_RECONCILE_INTERVAL_MS,
  ZOMBIE_EXECUTING_GRACE_MS,
  FILE_EXISTENCE_CHECK_INTERVAL,
  FILE_EXISTENCE_MISS_THRESHOLD,
  AGENT_CLUSTER_BASE_RADIUS,
  AGENT_CLUSTER_RADIUS_PER_AGENT,
  ORBIT_BASE_RADIUS,
  ORBIT_RADIUS_PER_ITEM,
  SATELLITE_ORBIT_GAP,
  SATELLITE_TYPES,
  FOLDER_BUBBLE_TYPES,
  GHOST_FADE_DURATION,
  PANEL_DEFAULT_WIDTH,
  PANEL_MIN_WIDTH,
  PANEL_MAX_WIDTH,
  TCP_TIMEOUT,
  POSITION_SAVE_INTERVAL,
  CHECKPOINT_BACKUP_GENERATIONS,
  APP_STATE_BACKUP_GENERATIONS,
  MAX_RECENTLY_CLOSED_TABS,
  DELETED_AGENT_TOMBSTONE_MAX,
  CHECKPOINT_EMPTY_GUARD_MIN_PRIOR,
  CHECKPOINT_SHRINK_GUARD_MIN_PRIOR,
  CHECKPOINT_SHRINK_GUARD_RATIO,
  CHECKPOINT_SHRINK_GUARD_ENABLED,
  ROOT_NODE_KEY_PREFIX,
  LEGACY_ROOT_NODE_KEY,
  BUBBLE_TEXT_WIDTH_RATIO,
  BUBBLE_TEXT_REF_SIZE,
  LAYOUT_CENTER_X,
  LAYOUT_CENTER_Y,
  PHYSICS_MAGNET_GAP,
  PHYSICS_REPULSION_STRENGTH,
  PHYSICS_REPULSION_RANGE,
  PHYSICS_DAMPING,
  PHYSICS_MAX_VELOCITY,
  PHYSICS_JITTER,
  PHYSICS_FPS,
  PHYSICS_SLEEP_THRESHOLD,
  PHYSICS_SLEEP_FRAMES,
  MODEL_CONTEXT_LIMITS,
  DEFAULT_CONTEXT_LIMIT,
  MODEL_PRICING,
  DEFAULT_PRICING,
  calculateTokenCost,
  MODEL_FAMILY_DEFAULTS,
  isKnownFamily,
  MODEL_SEED_ENTRIES,
  parseFamilyFromFullId,
  parseModelSemver,
  listModelFamilies,
  listEffortLevels,
  getModelPricing,
  getModelContextLimit,
  normalizeModelId,
  resolveModelPricing,
  resolveModelContextLimit,
  isPricingEstimated,
  resolveAliasToLatest,
  TOKEN_BYTES_RATIO,
  TOKEN_SUBAGENT_FETCH_CONCURRENCY,
  SYSTEM_PROMPT_ESTIMATE,
  TOOL_SCHEMA_ESTIMATE,
  GIT_STATUS_ESTIMATE,
  TOKEN_FIXED_CATEGORIES,
  estimateTokens,
  CONTEXT_SOURCE_IDS,
  CONTEXT_SOURCE_ID_LIST,
  CONTEXT_PLUGIN_ID_PREFIX,
  CONTEXT_PREVIEW_MAX_CHARS,
  CONTEXT_SPAWN_SWITCHES,
  CONTEXT_SCOPE_LEVELS,
  resolveContextEnabled,
  contextOverrideAt,
  contextInheritedAt,
  contextScopeStates,
  IFRAME_BUBBLE_HEIGHT,
  FRONTEND_SERVER_PATTERNS,
  LOOPBACK_SNIFF_URLS_PER_BASH,
  LOOPBACK_SNIFF_PROBE_TTL_MS,
  IFRAME_PROXY_PATH,
  IFRAME_LOG_SERVER_BUFFER_MAX,
  IFRAME_LOG_CLIENT_BUFFER_MAX,
  IFRAME_LOG_POLL_INTERVAL_MS,
  IFRAME_LOG_BATCH_MS,
  IFRAME_LOG_TAIL_BYTES,
  IFRAME_DEAD_GRACE_MS,
  SERVER_LOG_BUFFER_MAX,
  SERVER_LOG_CLIENT_BUFFER_MAX,
  SERVER_LOG_BATCH_MS,
  SERVER_LOG_RECENT_VIEW_LIMIT,
  PIPELINE_CHILD_CONFIGS,
  PIPELINE_TYPE_INFO,
  PIPELINE_PARENT_BUBBLE_ID,
  AVAILABLE_AGENT_MODELS,
  AVAILABLE_AGENT_MODEL_FULL_IDS,
  AVAILABLE_AGENT_MODEL_IDS,
  isOpusModel,
  supportsFastMode,
  isForwardSubagentTextEnabled,
  isThinkingEnabled,
  AVAILABLE_AGENT_TOOLS,
  BACKFILL_AGENT_TOOLS,
  AGENT_TOOLS_BACKFILL_GEN,
  backfillAgentTools,
  CLI_BUILTIN_TOOLS,
  LEGACY_AGENT_TOOLS,  ASK_USER_QUESTION_TIMEOUT_MS,
  CLAUDE_VERSION_PROBE_TIMEOUT_MS,
  CLAUDE_INSTALL_SCAN_MAX,
  CLAUDE_SETUP_INSTALL_COMMAND_WIN,
  CLAUDE_SETUP_INSTALL_COMMAND_POSIX,
  CLAUDE_SETUP_DOCS_URL,
  CLAUDE_SETUP_INSTALL_TIMEOUT_MS,
  CLAUDE_SETUP_VERIFY_RETRY_INTERVAL_MS,
  CLAUDE_SETUP_VERIFY_RETRY_MAX,
  CLAUDE_SETUP_OUTPUT_MAX_CHARS,
  CLAUDE_SETUP_READY_HOLD_MS,
  CLAUDE_AUTO_UPDATE_BOOT_DELAY_MS,
  HOOK_TRANSPORT_REFRESH_DELAY_MS,  LOCKED_AGENT_TOOLS,
  AVAILABLE_PERMISSION_MODES,
  PERMISSION_MODES_WITHOUT_PROMPT,
  PERMISSION_MODE_CLI_VALUES,
  toCliPermissionMode,
  normalizeAgentDefinitionName,
  buildAgentsFlagJson,
  normalizePluginDirs,
  AVAILABLE_SETTING_SOURCES,
  AVAILABLE_AUTOCOMPACT_VALUES,
  AUTOCOMPACT_OFF,
  AUTOCOMPACT_COST_SAMPLE,
  DEFAULT_AUTOCOMPACT,
  DEFAULT_AUTOCOMPACT_TOKENS,
  isAutoCompactOn,
  resolveAutoCompact,
  autoCompactThresholdTokens,
  turnCompactTriggerTokens,
  TURN_COMPACT_TRIGGER_RATIO,
  shouldCompactAfterTurn,
  AGENT_COMPACT_COMMAND,
  displayCommands,
  isInternalSlashCommand,
  withoutSlashCommandFlag,
  buildAgentSelfCompactRule,
  DEFAULT_AGENT_CONFIG,
  AGENT_MEMORY_SCOPES,
  normalizeAgentMemoryScope,
  SUBAGENT_DEPTH_MIN,
  SUBAGENT_DEPTH_MAX,
  normalizeSubagentDepth,
  BASH_TIMEOUT_MS_MIN,
  BASH_TIMEOUT_MS_MAX,
  BASH_DEFAULT_TIMEOUT_MS_CLI_DEFAULT,
  BASH_MAX_TIMEOUT_MS_CLI_DEFAULT,
  normalizeBashTimeoutMs,
  AVAILABLE_ISOLATION_MODES,
  AVAILABLE_EFFORT_LEVELS,
  EFFORT_LEVEL_PROBE_CANDIDATES,
  parseModelFamily,
  TASK_EDGE_TEMPLATES,
  TASK_EDGE_STYLES,
  TASK_EDGE_KIND_STYLES,
  TASK_EDGE_DEFAULTS,
  TASK_EDGE_DISPATCH_DEFAULT_TIMEOUT_MS,
  TASK_EDGE_CRITIQUE_MAX_REWORK_LIMIT,
  AUTO_AGENT_RUN_MAX_PER_AGENT,
  AUTO_AGENT_RUN_DEFAULT_REWORK_BUDGET,
  VERIFICATION_VERDICT_SCHEMA_GUIDE,
  TASK_EDGE_AUTO_REWORK_COMMAND_LABEL,
  GIT_STATUS_CONFIG,
  COMMENT_BOX_DEFAULTS,
  COMMENT_BOX_LOD,
  CANVAS_LOD,
  LINK_FOCUS,
  TIDY_BAND_ORDER,
  TIDY_LAYOUT,
  TIDY_SORTS,
  DEFAULT_TIDY_SORT,
  normalizeTidySort,
  tidyGeometryOf,
  LAYOUT_BOUNDS_DEFAULT,
  COMMENT_BOX_PALETTE,
  SESSION_MEMO,
  SESSION_MEMO_PALETTE,
  SESSION_MEMO_DEFAULT_COLOR,
  SESSION_MEMO_LEGACY_COLOR_MAP,
  CAPTURE_BUBBLE_DEFAULTS,
  CAPTURE_SNAP,
  CAPTURE_PLAYTEST,
  SUPPORTED_UI_LOCALES,
  LOCALE_META,
  DEFAULT_UI_LOCALE,
  AVAILABLE_CUSTOM_MODES,
  AVAILABLE_EXECUTION_MODES,
  CMD_CLI_KINDS,
  resolveCmdCliKind,
  TERMINAL_SCROLLBACK_LINES,
  TERMINAL_SCROLLBACK_MIN,
  TERMINAL_SCROLLBACK_MAX,
  TERMINAL_SCROLLBACK_BYTES_PER_LINE,
  clampTerminalScrollback,
  TERMINAL_RESIZE_DEBOUNCE_MS,
  CMD_RESIZE_REPAINT_MS,
  isConsoleRepaintChunk,
  shouldBufferPtyChunk,
  CMD_PREFILL_DELAY_MS,
  CMD_PREFILL_MAX_DEFER_MS,
  cmdPrefillDelay,
  CMD_STATE_TICK_MS,
  CMD_BLOCKED_IDLE_MS,
  CMD_IDLE_MS,
  CMD_BLOCK_TAIL_LINES,
  CMD_BLOCK_REASON_MAX,
  CMD_BLOCK_PATTERNS,
  CMD_PROCESS_POLL_MS,
  CMD_WAIT_MAX_MS,
  CMD_WAIT_POLL_MS,
  CMD_READ_MAX_LINES,
  CMD_SEND_MAX_CHARS,
  CMD_SEND_CONTROL_CHARS,
  sanitizeCmdPrefill,
  CMD_PANE_RATIO_MIN,
  CMD_PANE_RATIO_MAX,
  CMD_PANE_MAX,
  CMD_PANE_SEPARATOR,
  sanitizeCmdPaneTree,
  normalizeMemoName,
  repairMemoGroups,
  sanitizeSessionMemo,
  sanitizeSessionMemos,
  collectCmdPaneIds,
  cmdPaneTermId,
  splitCmdPane,
  closeCmdPane,
  resizeCmdPane,
  CMD_AGENT_COLOR,
  CONTI_DEFAULTS,
  CONTI_AGENT_RULES,
  STAMP_CATALOG,
  // §5.13 (Q) 대본 → 콘티 → 렌더
  STORYBOARD_PRESETS,
  STORYBOARD_PRESET_IDS,
  DEFAULT_STORYBOARD_PRESET_ID,
  resolveStoryboardPreset,
  normalizeStoryboardPresetId,
  CONTI_SCRIPT_MAX_CHARS,
  CONTI_SCRIPT_EXCERPT_MAX,
  CONTI_SCRIPT_FRAME_MIN,
  CONTI_SCRIPT_FRAME_MAX,
  RULES_HISTORY_MAX,
  CANVAS_CLIPBOARD_STORAGE_KEY,
  CANVAS_CLIPBOARD_SCHEMA_VERSION,
  CANVAS_CLIPBOARD_DEFAULT_PASTE_OFFSET,
  DIAGNOSTIC_LOG_MAX,
  STREAM_EVENTS_MAX_PER_SESSION,
  STREAM_EVENTS_TRIM_SLACK,
  STREAM_EVENTS_MAX_PER_INACTIVE_SESSION,
  STREAM_INACTIVE_SESSIONS_MAX,
  UPDATE_CHECK_INTERVAL_MS,
  UPDATE_FEED_URL,
  UPDATE_FEED_PROBE_TIMEOUT_MS,
  AUTO_AGENT_LAYOUT_RADIUS,
  AUTO_AGENT_MAX_CLARIFYING_QUESTIONS,
  AUTO_AGENT_ROLE_POLICY,
  AUTO_AGENT_TEMPLATES,
  AUTO_AGENT_DEFAULT_RULES,
  AUTO_AGENT_BUILDER_CONFIG,
  AUTO_AGENT_BUILDER_INTERVIEW_TOOL,
  buildHarnessBuilderRules,
  AGENT_REPORT_MAX_PER_AGENT,
  AGENT_INTENT_FIRST_RULES,
  buildAgentCardCommonRules,
  CARD_RULES_DOCUMENT,
  buildAgentReportRules,
  AGENT_CARD_ENV_BASE,
  AGENT_CARD_ENV_TOKEN,
  LOOPBACK_INGRESS_HEADER,
  LOOPBACK_INGRESS_VALUE,
  AGENT_QUESTIONS_MAX_PER_AGENT,
  buildAgentQuestionRules,
  AGENT_REVIEWS_MAX_PER_AGENT,
  STREAM_DENSITIES,
  STREAM_DIFF_AUTO_EXPAND_MAX_LINES,
  DIFF_COMMENT_MAX,
  PREVIEW_PICK_SOURCE,
  PREVIEW_PICK_TEXT_MAX,
  PREVIEW_ALT_MESSAGE,
  PREVIEW_ALT_CAPTURE_MESSAGE,
  PREVIEW_ALT_CAPTURE_DEFAULT,
  PREVIEW_HOVER_MESSAGE,
  PREVIEW_DEVICE_PRESETS,
  PREVIEW_SNIP_MIN_PX,
  resolveCompareWidths,
  STREAM_COMPACT_TEXT_CLAMP_LINES,
  STREAM_COMPACT_TEXT_CLAMP_CHARS,
  STREAM_COMPACT_TEXT_TAIL_LINES,
  STREAM_COMPACT_TEXT_TAIL_CHARS,
  STREAM_COMPACT_TEXT_MIN_HIDDEN_CHARS,
  STREAM_COMPACT_LIST_PREVIEW,
  STREAM_COMPACT_SUMMARY_CHARS,
  buildAgentReviewRules,
  AGENT_LISTS_MAX_PER_AGENT,
  PLAY_BUBBLE_DEFAULT_WIDTH,
  PLAY_BUBBLE_DEFAULT_HEIGHT,
  PLAY_PREVIEW_DEFAULT_WIDTH,
  PLAY_PREVIEW_DEFAULT_HEIGHT,
  PLAY_PREVIEW_GAP,
  PLAY_START_TIMEOUT_MS,
  PLAY_PROBE_INTERVAL_MS,
  PLAY_ALIVE_SWEEP_MS,
  PLAY_STATIC_INDEX_FILES,
  PLAY_STATIC_ROOT_DIRS,
  buildPlayRecipeAskPrompt,
  SPEC_BUBBLE_DEFAULT_WIDTH,
  SPEC_BUBBLE_DEFAULT_HEIGHT,
  SPEC_TITLE_MAX,
  SPEC_ITEM_TEXT_MAX,
  SPEC_BODY_MAX,
  SPEC_MAX_ITEMS,
  SPEC_TASK_LABEL_MAX,
  REVIEW_DIFF_MAX_BYTES,
  REVIEW_FILES_MAX,
  REVIEW_REQUESTS_MAX_PER_PROJECT,
  REVIEW_DECISIONS_MAX,
  REVIEW_REASON_MAX,
  REVIEW_REJECT_FILES_MAX,
  SPEC_TASK_OFFSET_X,
  SPEC_TASK_GAP_Y,
  SPEC_RULES_BEGIN,
  SPEC_RULES_END,
  buildSpecTaskRules,
  LAB_BUBBLE_DEFAULT_WIDTH,
  LAB_BUBBLE_DEFAULT_HEIGHT,
  LAB_TITLE_MAX,
  LAB_VARIANT_LABEL_MAX,
  LAB_TASK_MAX,
  LAB_RULES_APPEND_MAX,
  LAB_SUMMARY_MAX,
  LAB_MAX_VARIANTS,
  LAB_RUNS_MAX_PER_PROJECT,
  LAB_WORKTREE_PREFIX,
  WORKTREE_REAP_SETTLE_MS,
  LAB_CARD_OFFSET_X,
  LAB_CARD_GAP_Y,
  LAB_RULES_BEGIN,
  LAB_RULES_END,
  buildLabVariantRules,
  estimateLabCostUsd,
  SHELF_BUBBLE_DEFAULT_WIDTH,
  SHELF_BUBBLE_DEFAULT_HEIGHT,
  SHELF_MAX_ITEMS,
  SHELF_BUBBLES_MAX_PER_PROJECT,
  SHELF_TITLE_MAX,
  SHELF_LABEL_MAX,
  SHELF_COMMAND_MAX,
  SHELF_PROMPT_MAX,
  SHELF_RUN_TIMEOUT_MS,
  SHELF_RUN_OUTPUT_MAX_CHARS,
  SHELF_EXPORT_VERSION,
  SHELF_CARD_OFFSET_X,
  SHELF_IMPORT_MAX_ITEMS,
  SHELF_ICONS,
  SHELF_DEFAULT_ICON,
  SHELF_ITEM_COLORS,
  SHELF_DEFAULT_ITEM_COLOR,
  normalizeShelfIcon,
  normalizeShelfColor,
  normalizeShelfImport,
  COST_MAP_SWEEP_INTERVAL_MS,
  COST_MAP_ACTIVE_WINDOW_MS,
  COST_MAP_SESSIONS_MAX,
  COST_MAP_AGENTS_MAX,
  COST_MAP_DAYS_MAX,
  COST_WARN_USD,
  COST_DANGER_USD,
  COST_PERIODS,
  COST_MAP_UNSEEDED_MODELS_MAX,
  emptyCostTotals,
  addCostTotals,
  costTokenTotal,
  hasCostActivity,
  costDayKey,
  costPeriodStart,
  isCostDayInPeriod,
  sumCostDays,
  buildCostPeriodTotals,
  costTone,
  formatCostUsd,
  formatTokenCount,
  // §5.22 — 권한·감사 경계(판정은 서버·클라 공용 순수 함수 한 곳).
  AUDIT_RISK_KINDS,
  AUDIT_ENTRIES_MAX_PER_PROJECT,
  AUDIT_SUMMARY_MAX_CHARS,
  AUDIT_TARGET_MAX_CHARS,
  AUDIT_REASON_MAX_CHARS,
  AUDIT_TIMELINE_PAGE_SIZE,
  AUDIT_SNAPSHOT_ENTRIES,
  AUDIT_WRITE_TOOLS,
  AUDIT_NETWORK_TOOLS,
  AUDIT_DELETE_PATTERNS,
  AUDIT_NETWORK_PATTERNS,
  AUDIT_CONFIG_PATH_PATTERNS,
  AUDIT_CONFIG_MUTATION_PATTERNS,
  AUDIT_URL_PATTERN,
  AUDIT_LOOPBACK_HOSTS,
  AUDIT_PATH_INPUT_TOOLS,
  AUDIT_PATH_INPUT_KEYS,
  AUDIT_ABSOLUTE_PATH_PATTERNS,
  AUDIT_HOME_PREFIX_PATTERN,
  AUDIT_MSYS_PATH_PATTERN,
  AUDIT_RELATIVE_ESCAPE_PATTERN,
  AUDIT_OUTSIDE_IGNORE_PATTERNS,
  AUDIT_TOKEN_WRAPPER_PATTERNS,
  AUDIT_TOKEN_FLAG_VALUE_PATTERN,
  AUDIT_FALLBACK_PATH_PLATFORM,
  DEFAULT_AUDIT_BOUNDARY,
  isAuditLoopbackTarget,
  isAuditPathOutside,
  classifyToolRisk,
  summarizeToolCall,
  isAuditRiskEnabled,
  shouldEscalateRisk,
  normalizeAuditBoundary,
  isDefaultAuditBoundary,
  emptyAuditCounts,
  // §5.26 — 컨텍스트 보험(판정·형식 상수. 보존 축은 위쪽 §3.2.3 블록에 있다).
  INSURANCE_DIR,
  INSURANCE_BLOBS_DIR,
  INSURANCE_TRANSCRIPTS_DIR,
  INSURANCE_HEAD_HASH_BYTES,
  INSURANCE_TAIL_MAX_CHARS,
  INSURANCE_WORKING_SET_MAX,
  INSURANCE_PREIMAGE_MAX_BYTES,
  INSURANCE_COMPACT_TIMEOUT_MS,
  INSURANCE_SUMMARY_SCAN_MAX_BYTES,
  INSURANCE_TITLE_SCAN_MAX_BYTES,
  INSURANCE_OVERDUE_RATIO,
  INSURANCE_STALL_RATIO,
  INSURANCE_COMPACT_SEND_TIMEOUT_MS,
  INSURANCE_OVERDUE_MS,
  INSURANCE_OVERDUE_GROWTH_BYTES,
  INSURANCE_BRIEF_MAX_CHARS,
  INSURANCE_LESSON_REPEAT,
  INSURANCE_RESUME_RISK_BYTES,
  INSURANCE_RESUME_SHORTFALL_RATIO,
  INSURANCE_SNAPSHOT_MARKERS,
  INSURANCE_SNAPSHOT_PREIMAGES,
  INSURANCE_LIST_PAGE_SIZE,
  AGENT_FEEDBACK_MAX_PER_AGENT,
  AGENT_FEEDBACK_DIGEST_MAX,
  AGENT_FEEDBACK_DISTILL_MAX,
  AGENT_FEEDBACK_SUMMARY_ITEM_MAX,
  buildAgentFeedbackBlock,
  COMMAND_DISPATCH_MODES,
  DEFAULT_COMMAND_DISPATCH_MODE,
  COMMAND_MERGE_SEPARATOR,
  normalizeCommandDispatchMode,
  // §5.5 #17-12 ③ — 실패 사유 코드 전량(화면이 문장을 고르는 기준. 클라가 자기 목록을 따로 두지 않는다).
  COMMAND_ERROR_CODES,
  COMMAND_ERROR_CODES_WITH_EXIT,
  // §5.5 #17-29 — 훅 버블 읽기 전용 경계(서버 REST 가드 · 클라 UI 가 같은 술어를 쓴다).
  isReadOnlyHookAgent,
  READ_ONLY_HOOK_AGENT_ERROR,
  SESSION_LOOP_MAX_ITERATIONS,
  SESSION_LOOP_DEFAULT_TOTAL,
  SESSION_LOOP_DEFAULT_INTERVAL_MS,
  SESSION_LOOP_MAX_INTERVAL_MS,
  SESSION_LOOP_COMMAND_MAX,
  VERIFICATION_RUNS_MAX_PER_SESSION,
  VERIFICATION_FOCUS_MAX,
  VERIFICATION_ATTEMPTS_MAX,
  VERIFICATION_REASON_MAX,
  VERIFICATION_ATTEMPT_TEXT_MAX,
  VERIFICATION_DEMO_MAX_PER_SESSION,
  VERIFICATION_DEMO_STEPS_MAX,
  VERIFICATION_DEMO_STEP_TEXT_MAX,
  VERIFICATION_DEMO_LABEL_MAX,
  VERIFICATION_DEMO_EXPECTED_MAX,
  VERIFICATION_DEMO_FRAMES_MAX,
  VERIFICATION_DEMO_DIR,
  VERIFY_SLASH_COMMAND,
  VERIFY_RECORDED_SKILL_PATH,
  SESSION_LOOP_COMPACT_COMMAND,
  SESSION_LOOP_CLEAR_COMMAND,
  SESSION_LOOP_PATH_MAX,
  SESSION_LOOP_MAX_COST_USD_LIMIT,
  SESSION_LOOP_MAX_DURATION_LIMIT_MS,
  SESSION_GOAL_TEXT_MAX,
  SESSION_GOAL_NOTE_MAX,
  SESSION_GOAL_HISTORY_MAX,
  SESSION_GOAL_STEPS_MAX,
  SESSION_GOAL_STEP_TEXT_MAX,
  SESSION_GOAL_PAST_TEXT_MAX,
  SESSION_GOAL_STEP_SKILLS_MAX,
  SVG_PATH_MAX,
  VISUAL_KIND_MAX,
  VISUAL_KIND_DORMANT_REF,
  VISUAL_KIND_TRASH_DAYS,
  VISUAL_KIND_SEEDS,
  VISUAL_KIND_STARTERS,
  GOAL_ACTION_MIN_REPEAT,
  GOAL_ACTION_SKILL_MIN_REPEAT,
  GOAL_ACTION_MAX,
  GOAL_ACTION_LABEL_MAX,
  GOAL_ACTION_PAYLOAD_MAX,
  VISUAL_SCENE_PATHS_MAX,
  VISUAL_SCENE_VIEWBOX,
  VISUAL_KIND_BLURB_MAX,
  VISUAL_KIND_SURFACES,
  // §5.5 #17-17 ㉒ — 무대 실황.
  STAGE_SURFACE_APPS,
  STAGE_WINDOW_FALLBACK_MS,
  VISUAL_SCENE_TEMPLATES,
  GOAL_FLOW_TEMPLATES,
  findSceneTemplate,
  applySceneTemplate,
  sanitizeGlyphPath,
  sanitizeScenePaths,
  normalizeKindSurface,
  sanitizeKindBlurb,
  mergeGoalSteps,
  buildSessionGoalRules,
  buildSessionGoalState,
  buildSessionGoalProtocol,
  VIBISUAL_CARD_SENTINEL,
  // §5.19 All Model — 로컬 LLM
  ALL_MODEL_INSTALL_ID,
  LOCAL_AGENT_COLOR,
  CODEX_AGENT_COLOR,
  LLAMA_RELEASE_LATEST_API,
  LLAMA_RELEASES_LIST_API,
  parseAssetSha256,
  LOCAL_ENGINE_DEFAULT_BACKENDS,
  LOCAL_MODEL_MAX_LOADED,
  LOCAL_MODEL_IDLE_UNLOAD_MS,
  LOCAL_ENGINE_PORT_BASE,
  LOCAL_ENGINE_BOOT_TIMEOUT_MS,
  HF_MODEL_API,
  LOCAL_MODEL_SEARCH_LIMIT,
  LOCAL_MODEL_FILE_LIMIT,
  LOCAL_MODEL_TOP_QUANT_COUNT,
  QUANT_POPULARITY,
  QUANT_RANK_UNKNOWN,
  quantRank,
  LOCAL_MODEL_CATALOG_SORTS,
  HF_SORT_FIELD,
  HF_EXPAND_FIELDS,
  LOCAL_ENGINE_DIR_NAME,
  LOCAL_MODEL_DIR_NAME,
  LOCAL_MODEL_OVERHEAD_RATIO,
  LOCAL_MODEL_OVERHEAD_BYTES,
  LOCAL_MODEL_RAM_USABLE_RATIO,
  classifyModelFit,
  LOCAL_DEFAULT_CONTEXT_SIZE,
  LOCAL_CONTEXT_MIN,
  LOCAL_CONTEXT_MAX,
  LOCAL_ANSWER_BUDGET_RATIO,
  LOCAL_ANSWER_BUDGET_MIN,
  localAnswerBudget,
  LOCAL_THINKING_BUDGET_RATIO,
  localThinkingBudget,
  LOCAL_MODEL_NON_CHAT_PIPELINE_TAGS,
  isChatCapablePipelineTag,
  LOCAL_TOOL_MAX_ROUNDS,
  LOCAL_TOOL_READ_MAX_BYTES,
  LOCAL_TOOL_RESULT_MAX_CHARS,
  LOCAL_ANSWER_BUDGET_RESERVE,
  LOCAL_TOOL_REPEAT_LIMIT,
  LOCAL_COMPACT_MAX_TOKENS,
  LOCAL_ENGINE_CACHE_REUSE,
  LOCAL_CHARS_PER_TOKEN,
  LOCAL_TOOL_RESULT_CONTEXT_RATIO,
  localToolResultBudget,
  LOCAL_HISTORY_CONTEXT_RATIO,
  localHistoryBudget,
  LOCAL_TOOL_LIST_MAX_ENTRIES,
  LOCAL_WEB_SEARCH_MAX_HITS,
  LOCAL_WEB_SEARCH_API_URL,
  LOCAL_WEB_SEARCH_TIMEOUT_MS,
  LOCAL_TOOL_COMMAND_TIMEOUT_MS,
  LOCAL_BASH_ESCAPE_PATTERNS,
  detectLocalBashEscape,
  LOCAL_TOOL_DEFS,
  LOCAL_TOOL_NAMES,
  LOCAL_READ_ONLY_TOOLS,
  LOCAL_EDIT_TOOLS,
  LOCAL_HOST_TOOLS,
  normalizeTodoStatus,
  LOCAL_PLANNING_TOOLS,
  LOCAL_EXIT_PLAN_TOOL,
  LOCAL_NETWORK_TOOLS,
  resolveLocalToolGate,
  shouldAskForTool,
  // §5.3 #12-1 — 권한 축은 사용자만 올린다(loopback 유입 동결).
  applyIngressPermissionGuard,
  canPromptForPermission,
  normalizeAgentProvider,
  ALL_MODEL_DEFAULT_LABEL_RE,
  // §5.25 Codex
  CODEX_SETUP_INSTALL_COMMAND,
  CODEX_SETUP_DOCS_URL,
  CODEX_SETUP_PROBE_TIMEOUT_MS,
  CODEX_SETUP_INSTALL_TIMEOUT_MS,
  CODEX_SETUP_VERIFY_RETRY_INTERVAL_MS,
  CODEX_SETUP_VERIFY_RETRY_MAX,
  CODEX_SETUP_OUTPUT_MAX_CHARS,
  CODEX_AUTH_PROBE_TIMEOUT_MS,
  CODEX_AUTH_LOGOUT_TIMEOUT_MS,
  CODEX_AUTH_POLL_INTERVAL_MS,
  CODEX_AUTH_LOGIN_POLL_INTERVAL_MS,
  CODEX_AUTH_LOGIN_TERM_ID,
  CODEX_AUTH_TERMINAL_REVEAL_MS,
  CODEX_HOME_ENV,
  CODEX_HOME_DIRNAME,
  CODEX_MODELS_CACHE_FILENAME,
  CODEX_HOOKS_FILENAME,
  CODEX_HOOK_MARKER,
  CODEX_HOOK_EVENTS,
  CODEX_PERMISSION_MAP,
  CODEX_PERMISSION_FALLBACK,
  resolveCodexPermission,
  CODEX_DEFAULT_LABEL_RE,
  providerForEngine,
  engineForProvider,
  agentModelLabelOf,
  buildCmdCardProtocolRules,
  MOBILE_PAIR_CODE_LENGTH,
  MOBILE_PAIR_MAX_ATTEMPTS,
  MOBILE_SESSION_MAX,
  MOBILE_SESSION_COOKIE,
  MOBILE_EXTERNAL_PAIR_CODE_LENGTH,
  MOBILE_PAIR_BAN_MS,
  MOBILE_UPNP_LEASE_S,
  MOBILE_QR_TICKET_TTL_MS,
  MOBILE_QR_TOKEN_BYTES,
  MOBILE_QR_MAX_USES,
  MOBILE_QR_PATH,
  MOBILE_QR_PARAM,
  MOBILE_VPN_ADAPTERS,
  MOBILE_VIRTUAL_ADAPTERS,
  CHAT_PAIR_TICKET_TTL_MS,
  CHAT_PAIR_TOKEN_BYTES,
  CHAT_PAIR_MAX_ATTEMPTS,
  CHAT_PAIR_BAN_MS,
  CHAT_PEER_MAX,
  CHAT_UNPAIRED_NOTICE_MS,
  CHAT_PENDING_ACTION_MAX,
  CHAT_LOG_AGENT_MAX,
  CHAT_PAIR_ATTEMPT_MAX,
  CHAT_TELEGRAM_API_BASE,
  CHAT_TELEGRAM_POLL_S,
  CHAT_TELEGRAM_MESSAGE_MAX,
  CHAT_DISCORD_API_BASE,
  CHAT_DISCORD_INTENTS,
  CHAT_DISCORD_HEARTBEAT_MISS_MAX,
  CHAT_DISCORD_ZOMBIE_CLOSE_CODE,
  CHAT_DISCORD_MESSAGE_MAX,
  CHAT_DISCORD_PAIR_COMMAND,
  CHAT_RECONNECT_MIN_MS,
  CHAT_RECONNECT_MAX_MS,
  CHAT_ACTION_TTL_MS,
  CHAT_LOG_DEFAULT_LINES,
  CHAT_LOG_MAX_LINES,
  CHAT_LOG_BUFFER_LINES,
  CHAT_BRIDGE_FILE,
  CHAT_PICK_MAX,
  CHAT_PICK_LABEL_MAX,
  CHAT_PICK_TOKEN_HEX,
  CHAT_PICK_AUTO_SESSION,
  CHAT_TARGETS_TTL_MS,
  DEFAULT_CHAT_VERBOSITY,
  COMPLETION_CHIME_DEDUPE_MS,
  USAGE_LIMIT_WARN_PCT,
  USAGE_LIMIT_DANGER_PCT,
  CLAUDE_USAGE_POLL_INTERVAL_MS,
  CLAUDE_USAGE_PROBE_TIMEOUT_MS,
  CLAUDE_AUTH_PROBE_TIMEOUT_MS,
  CLAUDE_AUTH_LOGOUT_TIMEOUT_MS,
  CLAUDE_AUTH_POLL_INTERVAL_MS,
  CLAUDE_AUTH_LOGIN_POLL_INTERVAL_MS,
  CLAUDE_AUTH_LOGIN_TERM_ID,
  CLAUDE_AUTH_TERMINAL_REVEAL_MS,
  BUILTIN_SLASH_COMMANDS,
  slashCommandNeedsTerminal,
  PLUGIN_SUPPORTED_CONTRIBUTIONS,
  PLUGIN_ID_PATTERN,
  APP_API_PREFIX,
  PLUGIN_API_PREFIX,
  SECRET_REDACTION_PATTERNS,
  SECRET_REDACTION_MASK,
  redactSecrets,
  // §5.11 정독 게이트 · §5.5 #17-44
  SPEC_DOC_ROOT_CANDIDATES,
  SPEC_DOC_EXTENSIONS,
  SPEC_DOC_SCAN_MAX_DEPTH,
  SPEC_DOC_FILE_MAX,
  SPEC_ID_PATTERN_DEFAULT,
  SPEC_UNIT_TOKEN_MAX,
  SPEC_ITEM_PATTERN_DEFAULT,
  SPEC_RESPLIT_DEPTH_MAX,
  SPEC_ITEM_LABEL_MAX,
  SPEC_TITLE_MIN_HITS,
  SPEC_TITLE_STOPWORDS,
  SPEC_RARE_TITLE_HIT_WEIGHT,
  SPEC_RARE_TITLE_DF_RATIO,
  SPEC_RARE_TITLE_MIN_UNITS,
  SPEC_TITLE_HEAD_PARTS,
  SPEC_DOC_SKIP_SEGMENTS,
  SPEC_DOC_SKIP_FILE_PATTERN,
  SPEC_DOC_LIST_MAX,
  SPEC_INDEX_SKIPPED_LIST_MAX,
  SPEC_CITATION_ACTUAL_MAX,
  SPEC_REQUIREMENT_MARKERS,
  SPEC_REQUIRED_MAX,
  SPEC_UNIT_MAX,
  SPEC_FULL_READ_LINE_MAX,
  SPEC_GREP_CONTEXT_LINES,
  SPEC_COVER_SATISFIED_RATIO,
  SPEC_STOP_RETRY_DEFAULT,
  SPEC_STOP_RETRY_LIMIT,
  SPEC_SPANS_PER_FILE_MAX,
  SPEC_LEDGER_SESSION_MAX,
  SPEC_GATE_EVENT_MAX,
  SPEC_LEDGER_FILE_MAX,
  SPEC_PROMPT_KEEP_CHARS,
  SPEC_TOUCHED_PATH_MAX,
  SPEC_CITATION_SESSION_MAX,
  SPEC_WIRE_FILE_MAX,
  SPEC_WIRE_SPANS_PER_FILE,
  SPEC_INDEX_TTL_MS,
  SPEC_CITATION_MIN_CHARS,
  SPEC_CITATION_MAX_CHARS,
  SPEC_SETTINGS_FILE,
  SPEC_GATE_STRENGTHS,
  SPEC_SCOPE_ENTRY_MAX,
  DEFAULT_SPEC_READING_SETTINGS,
  AUTO_GOAL_MIN_RUNS,
  AUTO_GOAL_SEQUENCE_MIN,
  AUTO_GOAL_SEQUENCE_MAX,
  AUTO_GOAL_WINDOW_MS,
  AUTO_GOAL_CANDIDATE_MAX,
  AUTO_GOAL_TITLE_MAX,
  AUTO_GOAL_STEP_MAX,
  AUTO_GOAL_DISMISSED_MAX,
  AUTO_GOAL_SCAN_TAIL,
  AUTO_GOAL_SKILL_BUDGET,
} from './constants.js';

// §5.3 #28 v1.60 — STAMP_CATALOG 메타 타입 (constants.ts 에 정의됨)
export type { StampSpec } from './constants.js';
/** §5.17 (A) — `compare` 가 나란히 놓는 폭 한 칸. */
export type { PreviewCompareWidth } from './constants.js';
/** §5.20 — 선반 가져오기 판정 결과(클라·서버 공용 순수 함수의 반환형). */
export type { ShelfImportDraftItem, ShelfImportResult } from './constants.js';
/** §5.5 #17-17 ⑪(a)(i) — 카드 씨앗·시작 카드가 공유하는 모양. */
export type { VisualKindPreset, VisualSceneTemplate, GoalFlowTemplate, GoalFlowTemplateStep, SceneTemplateMerge } from './constants.js';

// ─── §5.5 #17-17 ⑪(l) 무대 블록 — 코드블록처럼 끼워 넣는 진행 신고 ───
// 서버가 스트림에서 수확할 때와 클라가 대화에 그릴 때가 **같은 답**을 내야 하므로 파서는 여기 한 벌뿐이다.
export type {
  StageBlockStepStatus,
  StageBlockStep,
  StageBlockKind,
  StageBlockDirective,
  StageBlockSpan,
} from './stageBlock.js';
export {
  STAGE_BLOCK_LANGS,
  STAGE_BLOCK_KINDS_MAX,
  STAGE_BLOCK_STEPS_MAX,
  isStageBlockLang,
  extractStageBlocks,
  parseStageBlockBody,
  parseStageBlocks,
} from './stageBlock.js';

// §5.5 #17-17 ⑫ — 무대 팔레트: 배운 행동을 짓는 순수 집계.
export type { GoalActionInput } from './goalActions.js';
export { buildGoalActions } from './goalActions.js';

/** §5.21 — 금액 색조(배지·표 공용). */
export type { CostTone } from './constants.js';

// §5.22 — `outside` 판정에 넘기는 경계(프로젝트 루트·세션 cwd·플랫폼).
export type { AuditRiskOptions } from './constants.js';
// §5.13 (R) — 파일 하나를 무엇으로 여는가(클릭 지점 전부가 같은 판정을 쓴다).
export type { WorkspaceOpenAction, WorkspaceOpenAppClaim, WorkspaceOpenPlan, MediaConvertKind } from './constants.js';
export type { MediaToolsInfo, MediaConvertJob, MediaConvertStatus } from './types.js';

// §9 v3.89 — graph_snapshot 키맵 슬라이스 증분 (서버 인코딩 / 클라 복원 공용)
export { diffKeyedSlice, applyKeyedSliceDelta, DELTA_SLICE_KEYS } from './keyedSliceDelta.js';
export type { DeltaSliceKey } from './keyedSliceDelta.js';

// §9 — 스코프드 스냅샷 구독의 **슬라이스 축**(규칙 단일 소유는 `sliceScope.ts` 머리말).
export {
  SLICE_SCOPE_GROUPS,
  SLICE_SCOPE_GROUP_NAMES,
  SCOPABLE_SLICE_KEYS,
  ALWAYS_SHIPPED_SLICES,
  SLICE_TABLES_ARE_DISJOINT,
  isSliceScopeGroup,
  resolveSliceShipSet,
  stripScopedOutSlices,
  carryForwardScopedSlices,
} from './sliceScope.js';
export type { SliceScopeGroup, ScopableSliceKey, AlwaysShippedSliceKey } from './sliceScope.js';

// §3.2.4 F축 — 바이트 예산 LRU 캐시.
export { ByteBudgetCache, approximateStringBytes, capMapSize, capSetSize } from './byteBudgetCache.js';
// §5.3 #9-1 (P) — 조용한 선행 압축의 자리 판정(순수).
export { planSilentPreCompact } from './silentPreCompact.js';
export type { PreCompactQueueItem, PreCompactSlot, PreCompactPlan } from './silentPreCompact.js';
export type {
  ByteBudgetCacheOptions,
  ByteBudgetCacheStats,
  EvictableCache,
  SizeOf,
} from './byteBudgetCache.js';

// §3.2.4 H·I축 — 힙 계측 · 압력 대응 진단.
export type {
  MemorySample,
  MemoryPressureLevel,
  MemoryCacheStat,
  MemoryDiagnosticsReport,
} from './types.js';

// §5.5 v4.92 — 스트림 복원 예산 판정 (서버 저장 제외 / 클라 표시 필터 공용)
export {
  parseSystemSubtype,
  isNeverRenderedStreamEvent,
  THINKING_PULSE_SUBTYPE,
  HIDDEN_SYSTEM_SUBTYPES,
  isHiddenSystemSubtype,
  isNeverRenderedSystemSubtype,
  // §5.5 #17-13 ⑤-3 v5.08 — 작업 칩 payload (서버 발신 / 클라 합치기 공용)
  formatSystemChip,
  parseSystemTaskInfo,
  foldTaskBookend,
  SYSTEM_CHIP_TEXT_MAX,
  TASK_CHIP_START_SUBTYPE,
  TASK_CHIP_END_SUBTYPE,
  // §4 (CLI 사양 추종) — `--include-hook-events` 훅 줄 subtype
  HOOK_STREAM_SUBTYPES,
  isHookStreamSubtype,
} from './streamNoise.js';
export type { StreamNoiseProbe, StreamTaskInfo, StreamTaskStatus } from './streamNoise.js';

// §5.5 #17-20 v4.74 — 디버그·실행 런처 (A 실행 구성 / B MCP 프리셋 / C 외부 디버거)
export type {
  RunConfigSource,
  RunRuntime,
  RunConfigKind,
  RunConfig,
  RunConfigScanResult,
  McpPresetCategory,
  McpServerPreset,
  ExternalDebuggerId,
  ExternalDebuggerInfo,
} from './types.js';

// §5.5 #17-31 — 이 프로젝트에서 쓸 수 있는 MCP 인벤토리(글로벌·로컬·프로젝트·프리셋)
export type {
  McpServerScope,
  McpServerState,
  McpServerTransport,
  McpRequirementKind,
  McpRequirement,
  McpServerEntry,
  McpInventory,
} from './types.js';

// §5.5 #17-32 — 이 세션에 적용되는 Claude Code 훅 인벤토리(글로벌·프로젝트·로컬·정책)
export type {
  HookScope,
  HookLockReason,
  HookEntry,
  HookInventory,
  HookFiredPayload,
} from './types.js';
export { hookMatcherMatches, isWildcardHookMatcher } from './hookMatcher.js';

// §5.5 #17-33 — Claude Code 자신의 플러그인 체계(글로벌·이 프로젝트·마켓플레이스)
export type {
  ClaudePluginScope,
  ClaudePluginPlacement,
  ClaudePluginEntry,
  ClaudeMarketPlugin,
  ClaudeMarketplaceEntry,
  ClaudeMarketplaceKind,
  ClaudePluginInventory,
  ClaudePluginActionKind,
  ClaudePluginAutoRefreshSettings,
  ClaudePluginRefreshState,
  ClaudePluginRefreshResult,
} from './types.js';
export { resolvePluginPlacement, splitPluginId, normalizePluginPath, placementAppliesHere } from './claudePlugin.js';
export { KNOWN_CLAUDE_MARKETPLACES, classifyMarketplace, suggestedMarketplaces } from './claudePlugin.js';
// §5.5 #17-33 ⑦ — 갱신 판정. 화면 배지와 자동 갱신이 **같은 함수**를 읽어야 어긋나지 않는다.
export {
  comparePluginVersions,
  pluginsNeedingUpdate,
  annotatePluginUpdates,
  normalizePluginRefreshSettings,
  isPluginRefreshDue,
} from './claudePlugin.js';
export {
  CLAUDE_PLUGIN_REFRESH_DEFAULTS,
  CLAUDE_PLUGIN_REFRESH_MIN_INTERVAL_HOURS,
  CLAUDE_PLUGIN_REFRESH_MAX_INTERVAL_HOURS,
  CLAUDE_PLUGIN_REFRESH_STARTUP_DELAY_MS,
  CLAUDE_PLUGIN_REFRESH_TICK_MS,
  CLAUDE_PLUGIN_REFRESH_UPDATED_KEEP,
  CLAUDE_PLUGIN_REFRESH_MAX_PER_RUN,
} from './constants.js';

// §5.5 #17-2/#17-4 — 스킬 목록 한 줄. 목록에 있는 `plugin` 항목은 **실제로 실릴 수 있는 것**이어야 한다.
export type { AvailableSkill, AvailableSkillSource, SkillPluginState } from './types.js';
// §5.5 #17-33 ⑦ — 상태 태그. 세 자리(사이드바·에이전트 설정·`/` 자동완성)가 **이 한 함수**를 읽는다.
export { resolveSkillPluginState, skillFixAction, skillLoadsNow } from './claudePlugin.js';

export type { DebugLaunchRecipe } from './constants.js';
export {
  RUN_CONFIG_MAX,
  RUN_FAILURE_TAIL_LINES,
  RUN_OUTPUT_BUFFER_LINES,
  RUN_OUTPUT_FLUSH_MS,
  DEBUG_PORT_BASE,
  DEBUG_PORT_SCAN_MAX,
  DEBUG_LAUNCH_RECIPES,
  MCP_SERVER_PRESETS,
  detectRunRuntime,
  buildDebugCommand,
  findMcpPreset,
} from './constants.js';

// §5.5 #17-20 ⑩⑪ v4.94 — 공통 디버그 층(런타임 무관) + 출력 문제 매처
export type {
  DebugBackendKind,
  DebugAdapterTransport,
  DebugAttachKind,
  DebugAdapterSpec,
  DebugSessionStatus,
  DebugStoppedReason,
  DebugBreakpoint,
  DebugStackFrame,
  DebugVariable,
  DebugScope,
  DebugSessionState,
  DebugEventPayload,
  ProblemSeverity,
  ProblemMatch,
} from './types.js';
export type { ProblemMatcher } from './constants.js';
export {
  DEBUG_ADAPTER_PORT_TOKEN,
  DEBUG_ADAPTER_PORT_BASE,
  DEBUG_ADAPTER_READY_TIMEOUT_MS,
  DEBUG_REQUEST_TIMEOUT_MS,
  DEBUG_ADAPTERS,
  PROBLEM_MATCHERS,
  findDebugAdapter,
  matchProblemLine,
} from './constants.js';
export type { SessionRunState, SessionRunInputs, AgentBadgeShareInputs } from './sessionRunState.js';
export {
  EMPTY_SESSION_RUN_INPUTS,
  isSessionRunning,
  hasSessionWork,
  resolveSessionRunState,
  agentBadgeShare,
} from './sessionRunState.js';

// §2.4 (한도 정지) — "한도로 끊긴 턴"을 알아보는 판정 한 벌. 스트림 경로가 셋이라 여기 한 곳에 둔다.
export type { UsageLimitKind, UsageLimitStop } from './usageLimitStop.js';
export {
  USAGE_LIMIT_MESSAGE_MAX,
  USAGE_LIMIT_RESET_LABEL_MAX,
  USAGE_LIMIT_NOTICE_MAX,
  matchUsageLimitNotice,
  parseUsageLimitResetLabel,
  detectUsageLimitInText,
  detectUsageLimitStop,
} from './usageLimitStop.js';

// 경로 대소문자 정책 SSOT — Linux 는 대소문자를 구분하므로 무조건 소문자로 접으면 안 된다.
// shared 는 브라우저에서도 로드되므로 플랫폼은 인자로 받는다(pathCase.ts 머리말 참조).
export type { PlatformName } from './pathCase.js';

// §4 — 업데이트 전달 방식 판정(무서명 macOS 는 self-install). 플랫폼은 인자로 받는다.
export type { UpdateDeliveryInput } from './updateDelivery.js';
// §4 self-install — 받은 번들이 정말 이 아키텍처의 것인가. 파일 이름·피드를 믿지 않고
// Mach-O 헤더를 직접 읽는다. 아키텍처도 인자로 받는다(실기 없이 세 경우를 다 재기 위해).
export type { ProcessArch, MachoArch } from './machoArch.js';
export {
  MACHO_HEADER_PROBE_BYTES,
  readMachoArchs,
  isArchCompatible,
  toProcessArch,
} from './machoArch.js';
export {
  RELEASES_PAGE_BASE,
  resolveUpdateDelivery,
  releasesPageUrl,
  readUpdateDelivery,
  RELEASES_DOWNLOAD_BASE,
  macUpdateAssetName,
  macUpdateAssetUrl,
} from './updateDelivery.js';
// §4 — 업데이트 상태 전이 규칙. **받아 둔 것은 체크 결과로 지워지지 않는다**(sticky downloaded).
// 주기 체크가 실패했다는 이유로 이미 받아 둔 업데이트를 못 깔게 되던 것을 여기서 막는다.
export type { UpdateEvent } from './updateState.js';
export { reduceUpdateState, compareVersions, isNewerVersion } from './updateState.js';
// §5.10 — 자동 목표. 켬/끔 3층 판정 + 되풀이 절차 마이닝(모델 ❌ · 순수 함수).
export type {
  AutoGoalEnablement,
  AutoGoalScopeIds,
  AutoGoalScopeState,
} from './autoGoalScope.js';
export {
  AUTO_GOAL_SCOPE_ORDER,
  resolveAutoGoalEnabled,
  autoGoalActiveAnywhere,
  resolveAutoGoalProjectRoot,
  autoGoalScopeStates,
  withAutoGoalScope,
  withAutoGoalDismissed,
  capAutoGoalMap,
  normalizeAutoGoalSettings,
  normalizeAutoGoalScopeMap,
} from './autoGoalScope.js';
export type { AutoGoalMiningInput, AutoGoalMiningResult } from './autoGoalMining.js';
export {
  mineAutoGoalCandidates,
  autoGoalSequenceId,
  autoGoalTitle,
  autoGoalSkillBody,
  autoGoalSkillDescription,
  isSubsequenceRun,
} from './autoGoalMining.js';
// §5.5 #17-44 ⑧ — 정독 켬/끔 3층 판정(프로젝트·에이전트·세션). 서버·클라·플러그인이 같은 함수를 부른다.
export {
  SPEC_SCOPE_ORDER,
  resolveSpecReadingEnabled,
  specReadingScopeStates,
  withSpecReadingScope,
  capScopeMap,
  normalizeScopeMap,
} from './specReadingScope.js';
export type {
  SpecReadingEnablement,
  SpecReadingScopeIds,
  SpecReadingScopeState,
} from './specReadingScope.js';

// §4 — 업데이트 피드를 어디서 받는가. 기본은 GitHub 그대로이고, 프록시 주소가 설정돼 있고
// 실제로 닿을 때만 그쪽으로 간다(https 강제 · 닿지 않으면 폴백). 판정은 순수 함수라
// 세 플랫폼·네 실패 모양을 실기 없이 전부 시험할 수 있다.
export type { UpdateFeedInput, UpdateFeedChoice } from './updateFeed.js';
export { resolveUpdateFeed, updateFeedFileName } from './updateFeed.js';
// §3.7 — 바깥 브라우저 열기 실패 판정. 리눅스의 `shell.openExternal` 은 실패해도 resolve 하므로
// (xdg-open 을 wait=false 로 띄운다) 프라미스 대신 "열어 줄 프로그램이 있는가"를 잰다. 폴백 ❌.
export type {
  ExternalOpenFailureReason,
  ExternalOpenFailure,
  LinuxBrowserProbe,
  ExternalOpenNoticeInput,
} from './externalOpen.js';
export {
  LINUX_BROWSER_BINARIES,
  ALLOWED_EXTERNAL_SCHEMES,
  isAllowedExternalUrl,
  needsBrowserProbe,
  hasLinuxBrowserHandler,
  resolveExternalOpenNotice,
} from './externalOpen.js';
export {
  isCaseInsensitiveFs,
  isPathWithin,
  normalizePathShape,
  pathKey,
  legacyLowerPathKey,
  lookupByPath,
  samePath,
} from './pathCase.js';

// §2.1 #3 — Bash 명령에서 경로를 뽑는 공용 셸 파서. 토크나이저는 읽기(서버 `bashReadPaths.ts`)와
// 쓰기(여기)가 한 벌을 나눠 쓴다. 쓰기 추출기가 shared 인 이유는 §5.22 감사 원장의 `target` 도
// 같은 답을 봐야 하기 때문(`summarizeToolCall` 은 순수 함수라 서버 모듈을 부를 수 없다).
export {
  BASH_WRITE_PATH_LIMIT,
  SHELL_SEGMENT_SEPARATORS,
  tokenizeShellCommand,
  splitShellSegments,
  // heredoc 본문 걷어내기 — 읽기·쓰기가 **같은 함수**를 써야 한쪽만 뚫려 있지 않다(§2.1 #3).
  stripHeredocBodies,
  readHeredocDelimiter,
  normalizeShellCommandName,
  isUnusableShellArg,
  looksLikeShellPath,
  isAbsoluteShellPath,
  toNativeDriveShellPath,
  readShellCdTarget,
  extractBashWritePaths,
} from './bashCommandPaths.js';

// §5.23 — 도메인 버블의 공용 추출기. 서버 그래프(버블 세우기)와 §5.22 감사 원장(`target` 채우기)이
// **같은 함수**를 부른다 — 두 벌이 되면 "버블은 섰는데 원장은 비어 있는" 상태가 된다.
export type { WebToolExtraction } from './webToolEntry.js';
export {
  webNodeKey,
  webHostFromNodeKey,
  webHostFromUrl,
  clampWebText,
  readWebResponseText,
  readWebResponseError,
  extractResultHosts,
  extractResultCount,
  extractWebEntry,
} from './webToolEntry.js';

// §5.24 — 히트맵(읽기·쓰기 두 축). 서버가 `toolAxis()` 로 카운터를 가르고, 클라가 같은 파일의
// `heatValueOf`/`heatRatio`/`heatColor`/`heatSize`/`formatHeatCount` 로 그 값을 지름·색·숫자로
// 옮긴다. 판정이 두 벌이면 "숫자는 올랐는데 색이 안 변하는" 상태가 된다.
export type { HeatCounts, HeatCurve, HeatScale, ToolAxis } from './heatmap.js';
export {
  toolAxis,
  isHeatBubbleType,
  heatValueOf,
  heatRatio,
  heatColor,
  heatSize,
  formatHeatCount,
  heatQuantileSamples,
  heatCountAtRatio,
  heatLegendTicks,
  normalizeHeatCurve,
} from './heatmap.js';

// §2.1 — 외부 폴더 버블의 "무엇을 보여 줄까" 판정. 서버가 트리를 세울 때와 클라이언트가 그릴
// 때가 **같은 답**을 내야 한다(두 벌이 되면 한쪽만 고쳐져 화면과 숫자가 어긋난다).
export type { ExternalPlacePattern } from './constants.js';
export type {
  ExternalPlaceContext,
  ExternalPromotionInput,
  ExternalPromotionCandidate,
} from './externalFolderView.js';
export {
  externalPlaceKeyFor,
  externalPlaceHint,
  isVolatileSegment,
  volatileFoldTarget,
  volatilePlaceOf,
  externalPromotionScore,
  pickPromotedExternalFolders,
  normalizeExternalTopBudget,
} from './externalFolderView.js';

// §2.1 #3 — 편집 계열 도구(`Edit`/`MultiEdit`/`Write`/`NotebookEdit`)의 **입력 모양**을 아는
// 유일한 자리. 종전에는 클라 `IDE/diffTool.ts` 한 곳에만 있어 서버 그래프가 `MultiEdit`/
// `NotebookEdit` 를 아예 몰랐다(버블·쓰기 화살표·수정 이력 0). 셸 토크나이저와 같은 규율 —
// 파서가 두 벌이 되면 도구 입력이 바뀔 때 한쪽만 고쳐진다.
export type { EditToolHunk, EditToolMode, ParsedEditToolInput } from './editToolInput.js';
export {
  EDIT_INPUT_TOOLS,
  parseEditToolObject,
  parseEditToolInputJson,
  joinEditHunks,
} from './editToolInput.js';

// §4 — 개별 에이전트 설정이 설정 창의 전역 기본값과 어디서 갈라지는지. "미설정"의 표기가 필드마다
// 달라서(effort:'default' · isolation:'none' · maxTurns:0 · forwardSubagentText:undefined=켬)
// 접힘 규칙을 화면이 아니라 한 곳에 둔다.
export type { AgentConfigComparedField } from './agentConfigDiff.js';
export {
  AGENT_CONFIG_IDENTITY_FIELDS,
  AGENT_CONFIG_NON_INHERITED_FIELDS,
  AGENT_CONFIG_COMPARED_FIELDS,
  AGENT_MAX_TURNS_UI_FALLBACK,
  resolveAgentDefaults,
  resolveAgentConfig,
  sparsifyAgentConfig,
  hasAgentConfigOverrides,
  normalizeAgentFieldForCompare,
  agentFieldDiffers,
  diffAgentConfigFromDefaults,
} from './agentConfigDiff.js';

// §5.5 #17-6 (H-4) — 끌고 다니는 창의 "앱 안/밖" 판정. 창을 움직이는 쪽(Electron main)과
// 규칙이 갈라지지 않게 순수 함수 한 곳에 둔다(화면 API ❌ — 숫자만 본다).
export type { ScreenRect, AppEntryStep, RedockDwellStep } from './windowDragRegion.js';
export {
  DETACHED_REDOCK_INSET_PX,
  REDOCK_DWELL_MS,
  isCursorDeepInside,
  isCursorOutsideRect,
  stepAppEntry,
  stepRedockDwell,
} from './windowDragRegion.js';

// §5.5 #17-27 ⑮ — HTML 을 페이지로 여는 **경로형** 창구의 규약. 조립(클라 iframe src)과
// 해석(서버 라우트)이 갈라지면 화면에는 흰 사각형만 남으므로 한 파일에 둔다.
export type { WorkspaceSiteRequest, WorkspaceSiteInspectHit } from './workspaceSite.js';
export {
  WORKSPACE_SITE_PATH,
  WORKSPACE_HTML_EXTENSIONS,
  WORKSPACE_SITE_MIME_BY_EXT,
  WORKSPACE_SITE_REWRITE_MAX_BYTES,
  isWorkspaceHtmlPath,
  workspaceSiteMime,
  workspaceSiteBase,
  workspaceSiteUrl,
  parseWorkspaceSitePath,
  rewriteWorkspaceSiteHtml,
  rewriteWorkspaceSiteCss,
  workspaceSiteRewriteKind,
  WORKSPACE_SITE_REPORT_MESSAGE,
  workspaceSiteReporterScript,
  injectWorkspaceSiteAgents,
  WORKSPACE_SITE_SOURCE_ATTR,
  WORKSPACE_SITE_INSPECT_REQUEST,
  WORKSPACE_SITE_INSPECT_RESULT,
  annotateWorkspaceSiteSource,
  workspaceSiteInspectorScript,
} from './workspaceSite.js';

// 프리뷰 **안쪽 문서**의 스크롤바 톤. iframe 경계를 CSS 가 못 넘으므로, 페이지를 실어 보내는
// 두 자리(프리뷰 프록시 · 워크스페이스 사이트)가 같은 조각 하나를 함께 넣는다.
export {
  PREVIEW_SCROLLBAR_HOLD_MS,
  PREVIEW_SCROLLBAR_ACTIVE_ATTR,
  PREVIEW_SCROLLBAR_TRACK_VAR,
  previewScrollbarInjection,
} from './previewScrollbar.js';

// §5.5 #17-19 ⑦ — 탐색기가 만들거나 바꿔 다는 **이름**의 판정. 입력창(클라)과 디스크(서버)가
// 같은 규칙 하나를 봐야 "화면은 받아 줬는데 서버가 거절"이 생기지 않는다.
export type { WorkspaceEntryNameError } from './workspaceEntryName.js';
export {
  WORKSPACE_ENTRY_NAME_MAX,
  workspaceEntryNameError,
} from './workspaceEntryName.js';

// §7.11 — 루프백 주소 판정·별칭. 감지 폴백(서버)과 "눌러서 프리뷰"(클라)가 같은 규칙을 쓴다.
export {
  LOOPBACK_HOST_ALIASES,
  isLoopbackHostname,
  parseLoopbackUrl,
  isLoopbackPreviewUrl,
  loopbackUrlVariants,
  extractLoopbackUrls,
  isDocumentContentType,
  serverRootUrl,
  previewUrlForServer,
} from './loopbackUrl.js';

// §4 (첫 실행 온보딩) — ①설치 → ②로그인 → ③프로젝트 폴더. 세 게이트와 생성 REST 가 같은
// 순서 판정 하나를 봐야 "화면은 막았는데 서버는 만들어 준다"가 생기지 않는다.
export type { OnboardingStep, OnboardingInput } from './onboarding.js';
export {
  NO_PROJECT_FOLDER_ERROR,
  resolveOnboardingStep,
  isNoProjectFolderError,
} from './onboarding.js';

// §5.5 #17-38 — 음성 받아쓰기. 단축키 판정·커서 자리 끼워넣기·실패 사유 접기의 정본 한 곳.
export type {
  VoiceInputStatus,
  VoiceInputErrorCode,
  VoiceKeyLike,
  VoiceTextMerge,
  VoiceMicSettingsTarget,
} from './voiceInput.js';
export {
  VOICE_INPUT,
  isFatalVoiceError,
  mapVoiceError,
  mapMediaError,
  isVoiceToggleKey,
  voiceRecognitionLang,
  pushVoiceLevel,
  emptyVoiceLevels,
  levelFromTimeDomain,
  mergeVoiceText,
  micSettingsTarget,
  isMicAccessFixable,
  refineDeviceError,
  isNoDeviceError,
} from './voiceInput.js';

// §5.5 #17-38 ⑰⑱ — 마이크를 **어떻게 받을지**(에코 제거·잡음 억제)와 받아 온 글을 **어떻게
// 다듬을지**(한국어 띄어쓰기 복원). 위 voiceInput 이 "어디에 꽂을지"라면 이쪽은 그 앞뒤다.
export type { VoiceAudioProcessing } from './voiceAudio.js';
export {
  voiceAudioConstraints,
  readVoiceProcessing,
  shouldWarnEcho,
  polishVoiceChunk,
} from './voiceAudio.js';
// 띄어쓰기 규칙 본체 — 조사·어미 목록과 경계 판정은 그 자체로 한 덩어리라 파일을 나눴다.
export { respaceKorean, hasHangul } from './voiceKoSpacing.js';

// §5.5 #17-38 ⑫ — 오프라인 받아쓰기 엔진. 자산 고르기·모델 고르기·언어 등급·오디오 변환의 정본 한 곳.
export type {
  VoiceEngineAssetLike,
  VoiceModelRole,
  VoiceAsrLanguageTier,
  VoiceAsrInstallStage,
  VoiceAsrInstallProgress,
  VoiceAsrState,
} from './voiceAsr.js';
export {
  VOICE_ASR,
  VOICE_ASR_ENGINE_DIR_NAME,
  VOICE_ASR_MODEL_DIR_NAME,
  VOICE_ASR_RELEASE_SCAN_MAX,
  VOICE_MODEL_CHUNK_MS,
  VOICE_MODEL_DISK_APPROX_BYTES,
  SHERPA_RELEASES_LIST_API,
  SHERPA_ASR_MODELS_API,
  voiceEnginePlatformToken,
  voiceEngineArchToken,
  voiceEngineBinName,
  scoreVoiceEngineAsset,
  pickVoiceEngineAsset,
  scoreVoiceModelAsset,
  pickVoiceModelAsset,
  voiceModelAssetChunkMs,
  voiceModelRoleForFile,
  voiceModelDiskName,
  voiceAsrLanguageTier,
  voiceInstallPercent,
  isVoiceInstallRunning,
  downsampleTo16k,
  float32Bytes,
} from './voiceAsr.js';

// §5.26 / §7.23 — 세션 한 줄이 무엇에 대한 것이었나(첫 프롬프트 → 한 줄 제목).
export { sessionTitleFromPrompt, SESSION_TITLE_MAX_CHARS } from './sessionTitle.js';

// §5.10 (N) — 기억 정리를 에이전트에게 맡길 때 보내는 지시문. **UI 문자열이 아니라 지시문**이라

// §6 — 앱 단축키 SSOT. `COMMANDS` 한 표에서 실제 키 판정·화면 힌트·설정 화면·충돌 판정이
// 전부 나온다. 표에 없는 키는 힌트에도 설정에도 뜨지 않는다(거짓말하지 않는 것이 첫 규칙).
export type {
  CommandScope,
  CommandDef,
  CommandId,
  ParsedBinding,
  KeyEventLike,
  KeymapOverrides,
  BindingIssueKind,
  BindingIssue,
} from './keymap.js';
export {
  COMMANDS,
  commandDef,
  COMMAND_IDS,
  COMMAND_SCOPES,
  SCOPE_PARENT,
  PLACEHOLDER_KEYS,
  PLACEHOLDER_LABEL,
  OS_RESERVED_BINDINGS,
  scopeChain,
  scopeRelation,
  keyTokenFromCode,
  codesForKeyToken,
  parseBinding,
  formatBinding,
  normalizeBinding,
  expandBinding,
  matchesBinding,
  bindingFromEvent,
  isCommandId,
  defaultKeymap,
  normalizeKeymapOverrides,
  resolveKeymap,
  inspectBinding,
  blocksAssignment,
  findKeymapConflicts,
} from './keymap.js';

// ─── §5.5 #16-1 IDE 활동바 구성(순서·제외) 순수 로직 ───
export {
  normalizeIDEActivityBarPrefs,
  resolveActivityOrder,
  moveActivityItem,
  applyVisibleOrder,
} from './ideActivityBar.js';

// ─── §5.4 #14-4 "닫은 탭 다시 열기" 스택 (순수 로직) ───
export {
  closedTabDedupeKey,
  normalizeClosedTabEntries,
  pushClosedTabEntry,
  takeClosedTabEntry,
  pruneMissingClosedTabs,
} from './closedTabs.js';

// ─── §4 (판올림 번호 발급 대기) 모바일 접속 주소의 정체 판정 (순수 로직) ───
// 주소만 나열하면 Tailscale 의 `100.77.x.x` 와 진짜 랜 `192.168.x.x` 가 구별되지 않는다.
// 서버(desktop main)가 판정해 넘기고 클라이언트는 그대로 그린다 — 두 벌이 되면 어긋난다.
export type { MobileAdapterPattern } from './constants.js';
export type { MobileAddressKind, MobileAddressEntry, MobileAddressInput } from './mobileAddress.js';
export {
  MOBILE_ADDRESS_KIND_ORDER,
  MOBILE_QR_KIND_ORDER,
  isMobileAddressReachable,
  isCgnatAddress,
  isPrivateLanAddress,
  isLinkLocalAddress,
  classifyMobileAddress,
  buildMobileAddressEntries,
} from './mobileAddress.js';

// ─── §5.7 #24 세션 진입점 판정 (순수 로직) ───
// 종전 게이트는 `entrypoint === 'vscode'` 한 줄이라 "사용자가 직접 연 세션"이라는 **뜻**을
// VS Code 라는 **제품 이름**으로 적어 두고 있었다. 뜻은 술어(`isInteractiveEntrypoint`)로,
// 제품 이름은 그 안으로 넣는다 — 새 진입점은 술어 한 곳만 고치면 된다.
export type { SessionEntrypoint } from './sessionEntrypoint.js';
export {
  parseSessionEntrypoint,
  isInteractiveEntrypoint,
  entrypointFromConfigHome,
} from './sessionEntrypoint.js';

// ─── §3.6 Cowork 로컬 세션 디스크 규약 (순수 경로 계산) ───
// Cowork 는 설정 홈을 세션마다 따로 잡아 우리 `~/.claude/settings.json` 을 보지 않는다.
// 그 세션의 홈을 계산해 같은 훅 블록을 심으면 같은 코어가 같은 훅을 쏜다.
export type { CoworkPathEnv } from './coworkSessionPaths.js';
export {
  COWORK_SESSION_DIR_NAMES,
  COWORK_SESSION_DEPTH,
  claudeDesktopUserDataDir,
  coworkSessionRootDirs,
  isCoworkSessionDirName,
  coworkConfigHome,
  coworkSessionOutputsDir,
} from './coworkSessionPaths.js';

export type { ProviderUsage, ProviderUsageWindow } from './providerUsage.js';
