// §4 메신저 원격제어 브리지 — 봇이 폰에서 하는 말 (판올림 번호 발급 대기)
//
// **모달만 번역하고 카드를 한 언어로 두면, 그 사용자에게는 기능 전체가 읽을 수 없는 것이 된다.**
// 모달(`panel.remoteControl.*`)은 12개 로케일이 다 있는데 정작 폰으로 나가는 문구가 한국어
// 상수였다 — 영어권 사용자가 이 축을 켜면 봇이 한국어로만 말했다.
//
// main 프로세스에는 i18n 런타임이 없다(renderer 의 i18next 는 여기서 못 쓴다). 그래서
// §5.11 v4.58 플러그인 `strings.ts` 선례를 그대로 따른다 — **폴더가 자기 문자열을 들고 있고**,
// 고를 언어는 새 레일 없이 `GraphSnapshot.uiLocale` 에서 읽는다(chat/index.ts).
//
// 자리표시자는 `{이름}` 하나뿐이다(`fmt`). i18next 를 main 으로 끌어오지 않기 위한 선택이고,
// 복수형이 필요한 문장은 애초에 수를 앞에 두는 형태로 적어 언어별 복수 규칙을 타지 않게 했다.

import { DEFAULT_UI_LOCALE, SUPPORTED_UI_LOCALES } from '@vibisual/shared';
import type { UiLocale } from '@vibisual/shared';

/** 봇이 쓰는 문자열 한 벌. 키가 늘면 12개 로케일 전부 채워야 타입이 통과한다(그게 목적이다). */
export interface ChatStrings {
  // ─ 카드 머리글
  titlePermission: string;
  titleQuestion: string;
  titleReport: string;
  titleReview: string;
  titleGoal: string;
  titleStreamText: string;
  titleStreamThinking: string;
  titleStreamTool: string;
  titleHelp: string;
  titlePaired: string;
  titleNotPairing: string;
  titleDmOnly: string;
  titleUnpaired: string;
  titleNoAgents: string;
  titlePickAgent: string;
  titleTargetSet: string;
  titleNeedTarget: string;
  titleStatus: string;
  titleStop: string;
  titleSent: string;
  titleCannotSend: string;
  titleSendFailed: string;
  /** `{count}` */
  titleLog: string;

  // ─ 버튼
  btnAllow: string;
  btnDeny: string;

  // ─ 권한 카드
  /** `{tool}` */
  permTool: string;
  /** `{risks}` */
  permRisk: string;
  /** `{seconds}` */
  permAutoIn: string;

  // ─ 질문 카드
  /** `{count}` */
  askFirstOf: string;

  // ─ 작업 신고 / 검수
  reportUserActions: string;
  reportDid: string;
  reportNext: string;
  /** `{text}` */
  reviewInstruction: string;
  reviewChanges: string;
  reviewCheckpoints: string;

  // ─ 목표 / 진행
  /** `{done}` `{total}` `{percent}` */
  goalSteps: string;
  /** `{percent}` */
  goalPercent: string;
  goalNone: string;
  /** `{count}` */
  goalQueued: string;

  // ─ 스트림
  streamUnnamedTool: string;

  // ─ 안내문
  helpNotPaired1: string;
  helpNotPaired2: string;
  helpAgents: string;
  helpStatus: string;
  /** `{default}` `{max}` */
  helpLog: string;
  helpStop: string;
  helpUnpair: string;
  helpPlain: string;

  // ─ 페어링
  pairNotOpen1: string;
  pairNotOpen2: string;
  pairDmOnly1: string;
  pairDmOnly2: string;

  // ─ 버튼 회신
  ackExpired: string;
  ackAllowed: string;
  ackDenied: string;
  /** `{label}` */
  ackAnswered: string;
  ackTooLate: string;

  // ─ 명령 결과
  unpairDone: string;
  noAgents: string;
  /** `{label}` */
  currentTarget: string;
  noTarget: string;
  needTarget: string;
  targetSet: string;
  logEmpty: string;
  stopRequested: string;
  stopFailed: string;
  sendNoAgent: string;
  sendReadOnly: string;
  /** `{status}` */
  sendServerError: string;
}

const en: ChatStrings = {
  titlePermission: 'Permission needed',
  titleQuestion: 'Agent question',
  titleReport: 'Work report',
  titleReview: 'Ready for review',
  titleGoal: 'Goal',
  titleStreamText: 'Reply',
  titleStreamThinking: 'Thinking',
  titleStreamTool: 'Tool',
  titleHelp: 'How to use',
  titlePaired: 'Connected',
  titleNotPairing: 'Not accepting connections',
  titleDmOnly: 'Direct message only',
  titleUnpaired: 'Disconnected',
  titleNoAgents: 'No agents',
  titlePickAgent: 'Pick an agent',
  titleTargetSet: 'Agent selected',
  titleNeedTarget: 'Pick an agent first',
  titleStatus: 'Progress',
  titleStop: 'Stop',
  titleSent: 'Sent',
  titleCannotSend: 'Cannot send',
  titleSendFailed: 'Not sent',
  titleLog: 'Last {count} raw lines',
  btnAllow: 'Allow',
  btnDeny: 'Deny',
  permTool: 'Tool: {tool}',
  permRisk: 'Risk: {risks}',
  permAutoIn: 'Decided automatically in {seconds}s if you do not answer.',
  askFirstOf: '(first of {count} questions)',
  reportUserActions: 'For you to do',
  reportDid: 'Done',
  reportNext: 'Next',
  reviewInstruction: 'Asked: {text}',
  reviewChanges: 'Changed',
  reviewCheckpoints: 'To check',
  goalSteps: '{done}/{total} steps · {percent}%',
  goalPercent: '{percent}%',
  goalNone: 'No goal set right now.',
  goalQueued: '{count} command(s) queued',
  streamUnnamedTool: '(unnamed)',
  helpNotPaired1: 'This chat is not connected yet.',
  helpNotPaired2: 'Open File → Remote Control in Vibisual and scan the QR.',
  helpAgents: '/agents — pick the agent this chat talks to',
  helpStatus: '/status — what it is doing and how far along',
  helpLog: '/log [n] — last n raw lines (default {default}, max {max})',
  helpStop: '/stop — stop the current turn',
  helpUnpair: '/unpair — disconnect this chat',
  helpPlain: 'Anything else you type goes to the selected agent as a command.',
  pairNotOpen1: 'No connection is being accepted right now.',
  pairNotOpen2: 'Issue a fresh QR from File → Remote Control on the desktop.',
  pairDmOnly1: 'Pairing is only accepted in a one-to-one direct message.',
  pairDmOnly2: 'Send the same line to the bot in a DM instead of a shared channel.',
  ackExpired: 'That request already expired or was handled.',
  ackAllowed: 'Allowed.',
  ackDenied: 'Denied.',
  ackAnswered: 'Answered with "{label}".',
  ackTooLate: 'Too late — it was decided automatically.',
  unpairDone: 'This chat will no longer receive notifications.',
  noAgents: 'No agent can take commands yet.',
  currentTarget: 'Current agent: {label}',
  noTarget: 'None selected yet.',
  needTarget: 'Use /agents to pick the agent this chat talks to.',
  targetSet: 'What you type here now goes to this agent.',
  logEmpty: 'Nothing recorded yet.',
  stopRequested: 'Stop requested.',
  stopFailed: 'Could not stop it.',
  sendNoAgent: 'That agent is gone. Pick another one with /agents.',
  sendReadOnly: 'This agent is read-only (an external hook session).',
  sendServerError: 'The server answered {status}.',
};

const ko: ChatStrings = {
  titlePermission: '권한 승인 요청',
  titleQuestion: '에이전트 질문',
  titleReport: '작업 신고',
  titleReview: '검수 요청',
  titleGoal: '목표',
  titleStreamText: '응답',
  titleStreamThinking: '생각',
  titleStreamTool: '도구',
  titleHelp: '사용법',
  titlePaired: '연결되었습니다',
  titleNotPairing: '연결 대기 아님',
  titleDmOnly: '1:1 대화에서만',
  titleUnpaired: '연결을 끊었습니다',
  titleNoAgents: '에이전트 없음',
  titlePickAgent: '에이전트 고르기',
  titleTargetSet: '상대를 정했습니다',
  titleNeedTarget: '먼저 상대를 고르세요',
  titleStatus: '진행 상황',
  titleStop: '중지',
  titleSent: '보냈습니다',
  titleCannotSend: '보낼 수 없음',
  titleSendFailed: '보내지 못했습니다',
  titleLog: '원문 마지막 {count}줄',
  btnAllow: '허용',
  btnDeny: '거부',
  permTool: '도구: {tool}',
  permRisk: '위험: {risks}',
  permAutoIn: '{seconds}초 안에 답하지 않으면 자동으로 결정됩니다.',
  askFirstOf: '(질문 {count}개 중 첫 번째)',
  reportUserActions: '직접 하실 일',
  reportDid: '한 일',
  reportNext: '다음',
  reviewInstruction: '지시: {text}',
  reviewChanges: '고친 것',
  reviewCheckpoints: '확인할 것',
  goalSteps: '{done}/{total} 단계 · {percent}%',
  goalPercent: '{percent}%',
  goalNone: '지금 세운 목표가 없습니다.',
  goalQueued: '대기 중인 명령 {count}건',
  streamUnnamedTool: '(이름 없음)',
  helpNotPaired1: '이 대화는 아직 연결되지 않았습니다.',
  helpNotPaired2: 'Vibisual 의 File → Remote Control 에서 QR 을 발급해 스캔해 주세요.',
  helpAgents: '/agents — 에이전트를 골라 이 대화의 상대로 지정',
  helpStatus: '/status — 지금 하는 일과 진행률',
  helpLog: '/log [n] — 원문 마지막 n 줄 (기본 {default}, 최대 {max})',
  helpStop: '/stop — 지금 턴 중지',
  helpUnpair: '/unpair — 이 대화 연결 끊기',
  helpPlain: '그 밖의 글은 고른 에이전트에게 명령으로 전달됩니다.',
  pairNotOpen1: '지금은 새 연결을 받고 있지 않습니다.',
  pairNotOpen2: '데스크톱의 File → Remote Control 에서 QR 을 다시 발급해 주세요.',
  pairDmOnly1: '연결은 1:1 대화에서만 받습니다.',
  pairDmOnly2: '공용 채널 대신 봇에게 직접 메시지로 같은 줄을 보내 주세요.',
  ackExpired: '이미 만료되었거나 처리된 요청입니다.',
  ackAllowed: '허용했습니다.',
  ackDenied: '거부했습니다.',
  ackAnswered: '"{label}" 로 답했습니다.',
  ackTooLate: '이미 시간이 지나 자동으로 결정되었습니다.',
  unpairDone: '이 대화는 더 이상 알림을 받지 않습니다.',
  noAgents: '명령을 받을 수 있는 에이전트가 아직 없습니다.',
  currentTarget: '지금 상대: {label}',
  noTarget: '아직 고르지 않았습니다.',
  needTarget: '/agents 로 이 대화가 겨눌 에이전트를 골라 주세요.',
  targetSet: '이제 이 대화의 글은 이 에이전트로 갑니다.',
  logEmpty: '아직 기록된 줄이 없습니다.',
  stopRequested: '중지를 요청했습니다.',
  stopFailed: '중지에 실패했습니다.',
  sendNoAgent: '고른 에이전트를 찾지 못했습니다. /agents 로 다시 골라 주세요.',
  sendReadOnly: '이 에이전트는 읽기 전용입니다(외부 훅 세션).',
  sendServerError: '서버가 {status} 로 답했습니다.',
};

const ja: ChatStrings = {
  titlePermission: '権限の承認が必要です',
  titleQuestion: 'エージェントからの質問',
  titleReport: '作業報告',
  titleReview: 'レビュー依頼',
  titleGoal: '目標',
  titleStreamText: '応答',
  titleStreamThinking: '思考',
  titleStreamTool: 'ツール',
  titleHelp: '使い方',
  titlePaired: '接続しました',
  titleNotPairing: '接続を受け付けていません',
  titleDmOnly: 'ダイレクトメッセージのみ',
  titleUnpaired: '接続を解除しました',
  titleNoAgents: 'エージェントなし',
  titlePickAgent: 'エージェントを選ぶ',
  titleTargetSet: '相手を決めました',
  titleNeedTarget: '先に相手を選んでください',
  titleStatus: '進行状況',
  titleStop: '停止',
  titleSent: '送信しました',
  titleCannotSend: '送信できません',
  titleSendFailed: '送信できませんでした',
  titleLog: '生ログの最後 {count} 行',
  btnAllow: '許可',
  btnDeny: '拒否',
  permTool: 'ツール: {tool}',
  permRisk: 'リスク: {risks}',
  permAutoIn: '{seconds} 秒以内に答えないと自動で決定されます。',
  askFirstOf: '(質問 {count} 件のうち 1 件目)',
  reportUserActions: 'ご自身で行うこと',
  reportDid: '行ったこと',
  reportNext: '次に',
  reviewInstruction: '指示: {text}',
  reviewChanges: '直したこと',
  reviewCheckpoints: '確認すること',
  goalSteps: '{done}/{total} ステップ · {percent}%',
  goalPercent: '{percent}%',
  goalNone: '今は目標が設定されていません。',
  goalQueued: '待機中のコマンド {count} 件',
  streamUnnamedTool: '(名前なし)',
  helpNotPaired1: 'この会話はまだ接続されていません。',
  helpNotPaired2: 'Vibisual の File → Remote Control で QR を発行してスキャンしてください。',
  helpAgents: '/agents — この会話の相手にするエージェントを選ぶ',
  helpStatus: '/status — 今している作業と進捗',
  helpLog: '/log [n] — 生ログの最後 n 行 (既定 {default}、最大 {max})',
  helpStop: '/stop — 今のターンを停止',
  helpUnpair: '/unpair — この会話の接続を解除',
  helpPlain: 'それ以外の文は、選んだエージェントへの命令として送られます。',
  pairNotOpen1: '今は新しい接続を受け付けていません。',
  pairNotOpen2: 'デスクトップの File → Remote Control で QR を再発行してください。',
  pairDmOnly1: '接続は 1 対 1 のダイレクトメッセージでのみ受け付けます。',
  pairDmOnly2: '共有チャンネルではなく、ボットへの DM で同じ行を送ってください。',
  ackExpired: 'その要求はすでに期限切れか、処理済みです。',
  ackAllowed: '許可しました。',
  ackDenied: '拒否しました。',
  ackAnswered: '「{label}」と答えました。',
  ackTooLate: '時間が過ぎたため自動で決定されました。',
  unpairDone: 'この会話には今後、通知が届きません。',
  noAgents: '命令を受け取れるエージェントがまだありません。',
  currentTarget: '現在の相手: {label}',
  noTarget: 'まだ選んでいません。',
  needTarget: '/agents でこの会話の相手にするエージェントを選んでください。',
  targetSet: 'これ以降、この会話の文はこのエージェントへ送られます。',
  logEmpty: 'まだ記録された行がありません。',
  stopRequested: '停止を要求しました。',
  stopFailed: '停止できませんでした。',
  sendNoAgent: '選んだエージェントが見つかりません。/agents で選び直してください。',
  sendReadOnly: 'このエージェントは読み取り専用です(外部フックのセッション)。',
  sendServerError: 'サーバーが {status} を返しました。',
};

const zhCN: ChatStrings = {
  titlePermission: '需要授权',
  titleQuestion: '代理提问',
  titleReport: '工作汇报',
  titleReview: '请你验收',
  titleGoal: '目标',
  titleStreamText: '回复',
  titleStreamThinking: '思考',
  titleStreamTool: '工具',
  titleHelp: '使用方法',
  titlePaired: '已连接',
  titleNotPairing: '当前不接受连接',
  titleDmOnly: '仅限私聊',
  titleUnpaired: '已断开连接',
  titleNoAgents: '没有可用代理',
  titlePickAgent: '选择代理',
  titleTargetSet: '已选定代理',
  titleNeedTarget: '请先选择代理',
  titleStatus: '进度',
  titleStop: '停止',
  titleSent: '已发送',
  titleCannotSend: '无法发送',
  titleSendFailed: '发送失败',
  titleLog: '原文最后 {count} 行',
  btnAllow: '允许',
  btnDeny: '拒绝',
  permTool: '工具：{tool}',
  permRisk: '风险：{risks}',
  permAutoIn: '{seconds} 秒内不回答将自动决定。',
  askFirstOf: '(共 {count} 个问题中的第一个)',
  reportUserActions: '需要你做的',
  reportDid: '已完成',
  reportNext: '接下来',
  reviewInstruction: '指令：{text}',
  reviewChanges: '改动',
  reviewCheckpoints: '请确认',
  goalSteps: '{done}/{total} 步 · {percent}%',
  goalPercent: '{percent}%',
  goalNone: '目前没有设定目标。',
  goalQueued: '排队中的命令 {count} 条',
  streamUnnamedTool: '(无名称)',
  helpNotPaired1: '此对话尚未连接。',
  helpNotPaired2: '请在 Vibisual 的 File → Remote Control 中生成二维码并扫描。',
  helpAgents: '/agents — 选择此对话对应的代理',
  helpStatus: '/status — 当前在做什么以及进度',
  helpLog: '/log [n] — 原文最后 n 行(默认 {default}，最多 {max})',
  helpStop: '/stop — 停止当前这一轮',
  helpUnpair: '/unpair — 断开此对话',
  helpPlain: '其余文字都会作为命令发送给所选代理。',
  pairNotOpen1: '当前不接受新的连接。',
  pairNotOpen2: '请在桌面端 File → Remote Control 中重新生成二维码。',
  pairDmOnly1: '仅在一对一私聊中接受配对。',
  pairDmOnly2: '请不要在公共频道，改为私聊机器人并发送同一行。',
  ackExpired: '该请求已过期或已处理。',
  ackAllowed: '已允许。',
  ackDenied: '已拒绝。',
  ackAnswered: '已回答“{label}”。',
  ackTooLate: '时间已过，已自动决定。',
  unpairDone: '此对话将不再收到通知。',
  noAgents: '还没有能接受命令的代理。',
  currentTarget: '当前代理：{label}',
  noTarget: '尚未选择。',
  needTarget: '请用 /agents 选择此对话对应的代理。',
  targetSet: '此后你在这里输入的内容都会发给该代理。',
  logEmpty: '还没有记录。',
  stopRequested: '已请求停止。',
  stopFailed: '停止失败。',
  sendNoAgent: '找不到所选代理。请用 /agents 重新选择。',
  sendReadOnly: '该代理为只读(外部钩子会话)。',
  sendServerError: '服务器返回 {status}。',
};

const es: ChatStrings = {
  titlePermission: 'Permiso necesario',
  titleQuestion: 'Pregunta del agente',
  titleReport: 'Informe de trabajo',
  titleReview: 'Listo para revisar',
  titleGoal: 'Objetivo',
  titleStreamText: 'Respuesta',
  titleStreamThinking: 'Pensando',
  titleStreamTool: 'Herramienta',
  titleHelp: 'Cómo se usa',
  titlePaired: 'Conectado',
  titleNotPairing: 'No se aceptan conexiones',
  titleDmOnly: 'Solo por mensaje directo',
  titleUnpaired: 'Desconectado',
  titleNoAgents: 'Sin agentes',
  titlePickAgent: 'Elige un agente',
  titleTargetSet: 'Agente seleccionado',
  titleNeedTarget: 'Elige antes un agente',
  titleStatus: 'Progreso',
  titleStop: 'Detener',
  titleSent: 'Enviado',
  titleCannotSend: 'No se puede enviar',
  titleSendFailed: 'No se envió',
  titleLog: 'Últimas {count} líneas en bruto',
  btnAllow: 'Permitir',
  btnDeny: 'Denegar',
  permTool: 'Herramienta: {tool}',
  permRisk: 'Riesgo: {risks}',
  permAutoIn: 'Se decidirá solo en {seconds} s si no respondes.',
  askFirstOf: '(la primera de {count} preguntas)',
  reportUserActions: 'Lo que debes hacer tú',
  reportDid: 'Hecho',
  reportNext: 'Siguiente',
  reviewInstruction: 'Se pidió: {text}',
  reviewChanges: 'Cambios',
  reviewCheckpoints: 'Para comprobar',
  goalSteps: '{done}/{total} pasos · {percent}%',
  goalPercent: '{percent}%',
  goalNone: 'Ahora mismo no hay ningún objetivo.',
  goalQueued: '{count} comando(s) en cola',
  streamUnnamedTool: '(sin nombre)',
  helpNotPaired1: 'Este chat todavía no está conectado.',
  helpNotPaired2: 'Abre File → Remote Control en Vibisual y escanea el QR.',
  helpAgents: '/agents — elige el agente con el que habla este chat',
  helpStatus: '/status — qué está haciendo y cuánto lleva',
  helpLog: '/log [n] — últimas n líneas en bruto (por defecto {default}, máx. {max})',
  helpStop: '/stop — detener el turno actual',
  helpUnpair: '/unpair — desconectar este chat',
  helpPlain: 'Cualquier otro texto se envía al agente elegido como comando.',
  pairNotOpen1: 'Ahora mismo no se acepta ninguna conexión.',
  pairNotOpen2: 'Genera un QR nuevo desde File → Remote Control en el escritorio.',
  pairDmOnly1: 'El emparejamiento solo se acepta en un mensaje directo uno a uno.',
  pairDmOnly2: 'Envía la misma línea al bot por DM en lugar de en un canal compartido.',
  ackExpired: 'Esa solicitud ya caducó o se resolvió.',
  ackAllowed: 'Permitido.',
  ackDenied: 'Denegado.',
  ackAnswered: 'Se respondió «{label}».',
  ackTooLate: 'Demasiado tarde: se decidió automáticamente.',
  unpairDone: 'Este chat ya no recibirá avisos.',
  noAgents: 'Todavía no hay ningún agente que acepte comandos.',
  currentTarget: 'Agente actual: {label}',
  noTarget: 'Aún no has elegido ninguno.',
  needTarget: 'Usa /agents para elegir el agente con el que habla este chat.',
  targetSet: 'A partir de ahora lo que escribas aquí irá a este agente.',
  logEmpty: 'Todavía no hay nada registrado.',
  stopRequested: 'Se pidió detenerlo.',
  stopFailed: 'No se pudo detener.',
  sendNoAgent: 'Ese agente ya no está. Elige otro con /agents.',
  sendReadOnly: 'Este agente es de solo lectura (sesión de un hook externo).',
  sendServerError: 'El servidor respondió {status}.',
};

const es419: ChatStrings = {
  ...es,
  titleHelp: 'Cómo usarlo',
  ackAnswered: 'Se respondió "{label}".',
  permAutoIn: 'Se decide solo en {seconds} s si no respondes.',
  reportUserActions: 'Lo que tenés que hacer vos',
  helpNotPaired2: 'Abrí File → Remote Control en Vibisual y escaneá el QR.',
  pairNotOpen2: 'Generá un QR nuevo desde File → Remote Control en la computadora.',
  pairDmOnly2: 'Mandá la misma línea al bot por mensaje directo en vez de un canal compartido.',
  sendNoAgent: 'Ese agente ya no está. Elegí otro con /agents.',
  needTarget: 'Usá /agents para elegir el agente con el que habla este chat.',
};

const fr: ChatStrings = {
  titlePermission: 'Autorisation demandée',
  titleQuestion: "Question de l'agent",
  titleReport: 'Compte rendu',
  titleReview: 'À vérifier',
  titleGoal: 'Objectif',
  titleStreamText: 'Réponse',
  titleStreamThinking: 'Réflexion',
  titleStreamTool: 'Outil',
  titleHelp: 'Mode d’emploi',
  titlePaired: 'Connecté',
  titleNotPairing: 'Aucune connexion acceptée',
  titleDmOnly: 'Message privé uniquement',
  titleUnpaired: 'Déconnecté',
  titleNoAgents: 'Aucun agent',
  titlePickAgent: 'Choisir un agent',
  titleTargetSet: 'Agent sélectionné',
  titleNeedTarget: 'Choisissez d’abord un agent',
  titleStatus: 'Avancement',
  titleStop: 'Arrêt',
  titleSent: 'Envoyé',
  titleCannotSend: 'Envoi impossible',
  titleSendFailed: 'Non envoyé',
  titleLog: '{count} dernières lignes brutes',
  btnAllow: 'Autoriser',
  btnDeny: 'Refuser',
  permTool: 'Outil : {tool}',
  permRisk: 'Risque : {risks}',
  permAutoIn: 'Décision automatique dans {seconds} s si vous ne répondez pas.',
  askFirstOf: '(première de {count} questions)',
  reportUserActions: 'À faire de votre côté',
  reportDid: 'Fait',
  reportNext: 'Ensuite',
  reviewInstruction: 'Demande : {text}',
  reviewChanges: 'Modifications',
  reviewCheckpoints: 'À vérifier',
  goalSteps: '{done}/{total} étapes · {percent} %',
  goalPercent: '{percent} %',
  goalNone: 'Aucun objectif défini pour le moment.',
  goalQueued: '{count} commande(s) en attente',
  streamUnnamedTool: '(sans nom)',
  helpNotPaired1: 'Cette conversation n’est pas encore connectée.',
  helpNotPaired2: 'Ouvrez File → Remote Control dans Vibisual et scannez le QR.',
  helpAgents: '/agents — choisir l’agent auquel cette conversation parle',
  helpStatus: '/status — ce qu’il fait et où il en est',
  helpLog: '/log [n] — n dernières lignes brutes (par défaut {default}, max {max})',
  helpStop: '/stop — arrêter le tour en cours',
  helpUnpair: '/unpair — déconnecter cette conversation',
  helpPlain: 'Tout autre texte part vers l’agent choisi comme commande.',
  pairNotOpen1: 'Aucune nouvelle connexion n’est acceptée pour l’instant.',
  pairNotOpen2: 'Générez un nouveau QR depuis File → Remote Control sur le bureau.',
  pairDmOnly1: 'L’association ne se fait qu’en message privé, en tête-à-tête.',
  pairDmOnly2: 'Envoyez la même ligne au bot en message privé plutôt que dans un salon partagé.',
  ackExpired: 'Cette demande a déjà expiré ou a été traitée.',
  ackAllowed: 'Autorisé.',
  ackDenied: 'Refusé.',
  ackAnswered: 'Réponse envoyée : « {label} ».',
  ackTooLate: 'Trop tard — la décision a été prise automatiquement.',
  unpairDone: 'Cette conversation ne recevra plus de notifications.',
  noAgents: 'Aucun agent ne peut encore recevoir de commande.',
  currentTarget: 'Agent actuel : {label}',
  noTarget: 'Aucun choisi pour l’instant.',
  needTarget: 'Utilisez /agents pour choisir l’agent de cette conversation.',
  targetSet: 'Ce que vous écrivez ici part désormais vers cet agent.',
  logEmpty: 'Rien d’enregistré pour l’instant.',
  stopRequested: 'Arrêt demandé.',
  stopFailed: 'Impossible de l’arrêter.',
  sendNoAgent: 'Cet agent n’existe plus. Choisissez-en un autre avec /agents.',
  sendReadOnly: 'Cet agent est en lecture seule (session d’un hook externe).',
  sendServerError: 'Le serveur a répondu {status}.',
};

const de: ChatStrings = {
  titlePermission: 'Berechtigung nötig',
  titleQuestion: 'Frage des Agenten',
  titleReport: 'Arbeitsbericht',
  titleReview: 'Bitte prüfen',
  titleGoal: 'Ziel',
  titleStreamText: 'Antwort',
  titleStreamThinking: 'Denkt nach',
  titleStreamTool: 'Werkzeug',
  titleHelp: 'So geht’s',
  titlePaired: 'Verbunden',
  titleNotPairing: 'Keine Verbindungen möglich',
  titleDmOnly: 'Nur per Direktnachricht',
  titleUnpaired: 'Verbindung getrennt',
  titleNoAgents: 'Keine Agenten',
  titlePickAgent: 'Agent wählen',
  titleTargetSet: 'Agent ausgewählt',
  titleNeedTarget: 'Wähle zuerst einen Agenten',
  titleStatus: 'Fortschritt',
  titleStop: 'Stopp',
  titleSent: 'Gesendet',
  titleCannotSend: 'Senden nicht möglich',
  titleSendFailed: 'Nicht gesendet',
  titleLog: 'Letzte {count} Rohzeilen',
  btnAllow: 'Erlauben',
  btnDeny: 'Ablehnen',
  permTool: 'Werkzeug: {tool}',
  permRisk: 'Risiko: {risks}',
  permAutoIn: 'Wird in {seconds} s automatisch entschieden, wenn du nicht antwortest.',
  askFirstOf: '(erste von {count} Fragen)',
  reportUserActions: 'Das musst du selbst tun',
  reportDid: 'Erledigt',
  reportNext: 'Als Nächstes',
  reviewInstruction: 'Auftrag: {text}',
  reviewChanges: 'Geändert',
  reviewCheckpoints: 'Zu prüfen',
  goalSteps: '{done}/{total} Schritte · {percent} %',
  goalPercent: '{percent} %',
  goalNone: 'Derzeit ist kein Ziel gesetzt.',
  goalQueued: '{count} Befehl(e) in der Warteschlange',
  streamUnnamedTool: '(ohne Namen)',
  helpNotPaired1: 'Dieser Chat ist noch nicht verbunden.',
  helpNotPaired2: 'Öffne in Vibisual File → Remote Control und scanne den QR-Code.',
  helpAgents: '/agents — den Agenten wählen, mit dem dieser Chat spricht',
  helpStatus: '/status — was gerade läuft und wie weit',
  helpLog: '/log [n] — letzte n Rohzeilen (Standard {default}, max. {max})',
  helpStop: '/stop — den laufenden Zug stoppen',
  helpUnpair: '/unpair — diesen Chat trennen',
  helpPlain: 'Alles andere geht als Befehl an den gewählten Agenten.',
  pairNotOpen1: 'Derzeit wird keine neue Verbindung angenommen.',
  pairNotOpen2: 'Erzeuge am Desktop unter File → Remote Control einen neuen QR-Code.',
  pairDmOnly1: 'Die Kopplung wird nur in einer Eins-zu-eins-Direktnachricht angenommen.',
  pairDmOnly2: 'Schicke dieselbe Zeile per DM an den Bot statt in einen geteilten Kanal.',
  ackExpired: 'Diese Anfrage ist bereits abgelaufen oder erledigt.',
  ackAllowed: 'Erlaubt.',
  ackDenied: 'Abgelehnt.',
  ackAnswered: 'Mit „{label}“ geantwortet.',
  ackTooLate: 'Zu spät — es wurde automatisch entschieden.',
  unpairDone: 'Dieser Chat bekommt keine Meldungen mehr.',
  noAgents: 'Noch kann kein Agent Befehle annehmen.',
  currentTarget: 'Aktueller Agent: {label}',
  noTarget: 'Noch keiner gewählt.',
  needTarget: 'Wähle mit /agents den Agenten für diesen Chat.',
  targetSet: 'Was du hier schreibst, geht ab jetzt an diesen Agenten.',
  logEmpty: 'Noch nichts aufgezeichnet.',
  stopRequested: 'Stopp angefordert.',
  stopFailed: 'Konnte nicht gestoppt werden.',
  sendNoAgent: 'Diesen Agenten gibt es nicht mehr. Wähle mit /agents einen anderen.',
  sendReadOnly: 'Dieser Agent ist schreibgeschützt (Sitzung eines externen Hooks).',
  sendServerError: 'Der Server antwortete mit {status}.',
};

const it: ChatStrings = {
  titlePermission: 'Serve un permesso',
  titleQuestion: 'Domanda dell’agente',
  titleReport: 'Resoconto',
  titleReview: 'Da verificare',
  titleGoal: 'Obiettivo',
  titleStreamText: 'Risposta',
  titleStreamThinking: 'Sta pensando',
  titleStreamTool: 'Strumento',
  titleHelp: 'Come si usa',
  titlePaired: 'Collegato',
  titleNotPairing: 'Nessuna connessione accettata',
  titleDmOnly: 'Solo in messaggio diretto',
  titleUnpaired: 'Scollegato',
  titleNoAgents: 'Nessun agente',
  titlePickAgent: 'Scegli un agente',
  titleTargetSet: 'Agente scelto',
  titleNeedTarget: 'Scegli prima un agente',
  titleStatus: 'Avanzamento',
  titleStop: 'Stop',
  titleSent: 'Inviato',
  titleCannotSend: 'Impossibile inviare',
  titleSendFailed: 'Non inviato',
  titleLog: 'Ultime {count} righe grezze',
  btnAllow: 'Consenti',
  btnDeny: 'Nega',
  permTool: 'Strumento: {tool}',
  permRisk: 'Rischio: {risks}',
  permAutoIn: 'Deciso da solo tra {seconds} s se non rispondi.',
  askFirstOf: '(la prima di {count} domande)',
  reportUserActions: 'Cosa devi fare tu',
  reportDid: 'Fatto',
  reportNext: 'Poi',
  reviewInstruction: 'Richiesta: {text}',
  reviewChanges: 'Modifiche',
  reviewCheckpoints: 'Da controllare',
  goalSteps: '{done}/{total} passi · {percent}%',
  goalPercent: '{percent}%',
  goalNone: 'Al momento non c’è nessun obiettivo.',
  goalQueued: '{count} comando/i in coda',
  streamUnnamedTool: '(senza nome)',
  helpNotPaired1: 'Questa chat non è ancora collegata.',
  helpNotPaired2: 'Apri File → Remote Control in Vibisual e scansiona il QR.',
  helpAgents: '/agents — scegli l’agente con cui parla questa chat',
  helpStatus: '/status — cosa sta facendo e a che punto è',
  helpLog: '/log [n] — ultime n righe grezze (predefinito {default}, max {max})',
  helpStop: '/stop — ferma il turno in corso',
  helpUnpair: '/unpair — scollega questa chat',
  helpPlain: 'Qualsiasi altro testo va all’agente scelto come comando.',
  pairNotOpen1: 'Al momento non viene accettata nessuna nuova connessione.',
  pairNotOpen2: 'Genera un nuovo QR da File → Remote Control sul desktop.',
  pairDmOnly1: 'L’abbinamento si accetta solo in un messaggio diretto uno a uno.',
  pairDmOnly2: 'Manda la stessa riga al bot in DM invece che in un canale condiviso.',
  ackExpired: 'Quella richiesta è già scaduta o è stata gestita.',
  ackAllowed: 'Consentito.',
  ackDenied: 'Negato.',
  ackAnswered: 'Risposto «{label}».',
  ackTooLate: 'Troppo tardi: è stato deciso automaticamente.',
  unpairDone: 'Questa chat non riceverà più notifiche.',
  noAgents: 'Nessun agente può ancora ricevere comandi.',
  currentTarget: 'Agente attuale: {label}',
  noTarget: 'Non ne hai ancora scelto uno.',
  needTarget: 'Usa /agents per scegliere l’agente di questa chat.',
  targetSet: 'Da ora quello che scrivi qui va a questo agente.',
  logEmpty: 'Non c’è ancora nulla di registrato.',
  stopRequested: 'Stop richiesto.',
  stopFailed: 'Non è stato possibile fermarlo.',
  sendNoAgent: 'Quell’agente non c’è più. Scegline un altro con /agents.',
  sendReadOnly: 'Questo agente è di sola lettura (sessione di un hook esterno).',
  sendServerError: 'Il server ha risposto {status}.',
};

const ptBR: ChatStrings = {
  titlePermission: 'Permissão necessária',
  titleQuestion: 'Pergunta do agente',
  titleReport: 'Relato de trabalho',
  titleReview: 'Pronto para conferir',
  titleGoal: 'Objetivo',
  titleStreamText: 'Resposta',
  titleStreamThinking: 'Pensando',
  titleStreamTool: 'Ferramenta',
  titleHelp: 'Como usar',
  titlePaired: 'Conectado',
  titleNotPairing: 'Não aceitando conexões',
  titleDmOnly: 'Somente por mensagem direta',
  titleUnpaired: 'Desconectado',
  titleNoAgents: 'Sem agentes',
  titlePickAgent: 'Escolha um agente',
  titleTargetSet: 'Agente escolhido',
  titleNeedTarget: 'Escolha um agente primeiro',
  titleStatus: 'Progresso',
  titleStop: 'Parar',
  titleSent: 'Enviado',
  titleCannotSend: 'Não dá para enviar',
  titleSendFailed: 'Não enviado',
  titleLog: 'Últimas {count} linhas brutas',
  btnAllow: 'Permitir',
  btnDeny: 'Negar',
  permTool: 'Ferramenta: {tool}',
  permRisk: 'Risco: {risks}',
  permAutoIn: 'Será decidido sozinho em {seconds} s se você não responder.',
  askFirstOf: '(a primeira de {count} perguntas)',
  reportUserActions: 'O que você precisa fazer',
  reportDid: 'Feito',
  reportNext: 'A seguir',
  reviewInstruction: 'Pedido: {text}',
  reviewChanges: 'Mudanças',
  reviewCheckpoints: 'Para conferir',
  goalSteps: '{done}/{total} etapas · {percent}%',
  goalPercent: '{percent}%',
  goalNone: 'Nenhum objetivo definido agora.',
  goalQueued: '{count} comando(s) na fila',
  streamUnnamedTool: '(sem nome)',
  helpNotPaired1: 'Esta conversa ainda não está conectada.',
  helpNotPaired2: 'Abra File → Remote Control no Vibisual e escaneie o QR.',
  helpAgents: '/agents — escolher o agente com quem esta conversa fala',
  helpStatus: '/status — o que está fazendo e o quanto já andou',
  helpLog: '/log [n] — últimas n linhas brutas (padrão {default}, máx. {max})',
  helpStop: '/stop — parar o turno atual',
  helpUnpair: '/unpair — desconectar esta conversa',
  helpPlain: 'Qualquer outro texto vai como comando para o agente escolhido.',
  pairNotOpen1: 'Nenhuma conexão nova está sendo aceita agora.',
  pairNotOpen2: 'Gere um QR novo em File → Remote Control no computador.',
  pairDmOnly1: 'O pareamento só é aceito em mensagem direta, um a um.',
  pairDmOnly2: 'Mande a mesma linha para o bot por DM, não em um canal compartilhado.',
  ackExpired: 'Esse pedido já expirou ou já foi tratado.',
  ackAllowed: 'Permitido.',
  ackDenied: 'Negado.',
  ackAnswered: 'Respondido com "{label}".',
  ackTooLate: 'Tarde demais — foi decidido automaticamente.',
  unpairDone: 'Esta conversa não vai mais receber avisos.',
  noAgents: 'Ainda não há agente que aceite comandos.',
  currentTarget: 'Agente atual: {label}',
  noTarget: 'Nenhum escolhido ainda.',
  needTarget: 'Use /agents para escolher o agente desta conversa.',
  targetSet: 'A partir de agora o que você escrever aqui vai para este agente.',
  logEmpty: 'Nada registrado ainda.',
  stopRequested: 'Parada solicitada.',
  stopFailed: 'Não foi possível parar.',
  sendNoAgent: 'Esse agente sumiu. Escolha outro com /agents.',
  sendReadOnly: 'Este agente é somente leitura (sessão de um hook externo).',
  sendServerError: 'O servidor respondeu {status}.',
};

const hi: ChatStrings = {
  titlePermission: 'अनुमति चाहिए',
  titleQuestion: 'एजेंट का सवाल',
  titleReport: 'काम की रिपोर्ट',
  titleReview: 'जाँच के लिए तैयार',
  titleGoal: 'लक्ष्य',
  titleStreamText: 'जवाब',
  titleStreamThinking: 'सोच रहा है',
  titleStreamTool: 'टूल',
  titleHelp: 'इस्तेमाल कैसे करें',
  titlePaired: 'जुड़ गया',
  titleNotPairing: 'अभी कनेक्शन नहीं ले रहे',
  titleDmOnly: 'सिर्फ़ डायरेक्ट मैसेज में',
  titleUnpaired: 'कनेक्शन हटा दिया',
  titleNoAgents: 'कोई एजेंट नहीं',
  titlePickAgent: 'एजेंट चुनें',
  titleTargetSet: 'एजेंट चुन लिया',
  titleNeedTarget: 'पहले एजेंट चुनें',
  titleStatus: 'प्रगति',
  titleStop: 'रोकें',
  titleSent: 'भेज दिया',
  titleCannotSend: 'भेज नहीं सकते',
  titleSendFailed: 'नहीं भेजा गया',
  titleLog: 'आख़िरी {count} कच्ची लाइनें',
  btnAllow: 'अनुमति दें',
  btnDeny: 'मना करें',
  permTool: 'टूल: {tool}',
  permRisk: 'जोखिम: {risks}',
  permAutoIn: 'जवाब न देने पर {seconds} सेकंड में अपने आप तय हो जाएगा।',
  askFirstOf: '({count} सवालों में से पहला)',
  reportUserActions: 'आपको ख़ुद करना है',
  reportDid: 'जो किया',
  reportNext: 'आगे',
  reviewInstruction: 'निर्देश: {text}',
  reviewChanges: 'क्या बदला',
  reviewCheckpoints: 'क्या जाँचें',
  goalSteps: '{done}/{total} चरण · {percent}%',
  goalPercent: '{percent}%',
  goalNone: 'अभी कोई लक्ष्य तय नहीं है।',
  goalQueued: 'क़तार में {count} कमांड',
  streamUnnamedTool: '(बिना नाम)',
  helpNotPaired1: 'यह चैट अभी जुड़ी नहीं है।',
  helpNotPaired2: 'Vibisual में File → Remote Control खोलकर QR स्कैन करें।',
  helpAgents: '/agents — इस चैट का एजेंट चुनें',
  helpStatus: '/status — अभी क्या कर रहा है और कितना हुआ',
  helpLog: '/log [n] — आख़िरी n कच्ची लाइनें (डिफ़ॉल्ट {default}, अधिकतम {max})',
  helpStop: '/stop — चल रही बारी रोकें',
  helpUnpair: '/unpair — यह चैट अलग करें',
  helpPlain: 'बाक़ी जो लिखेंगे वह चुने हुए एजेंट को कमांड की तरह जाएगा।',
  pairNotOpen1: 'अभी कोई नया कनेक्शन नहीं लिया जा रहा।',
  pairNotOpen2: 'डेस्कटॉप पर File → Remote Control से नया QR बनाएँ।',
  pairDmOnly1: 'जोड़ी सिर्फ़ आमने-सामने वाले डायरेक्ट मैसेज में बनती है।',
  pairDmOnly2: 'साझा चैनल की जगह बॉट को DM में वही लाइन भेजें।',
  ackExpired: 'वह अनुरोध पहले ही ख़त्म हो चुका है या निपट चुका है।',
  ackAllowed: 'अनुमति दे दी।',
  ackDenied: 'मना कर दिया।',
  ackAnswered: '"{label}" से जवाब दिया।',
  ackTooLate: 'देर हो गई — अपने आप तय हो गया।',
  unpairDone: 'इस चैट पर अब सूचनाएँ नहीं आएँगी।',
  noAgents: 'अभी कोई एजेंट कमांड नहीं ले सकता।',
  currentTarget: 'अभी का एजेंट: {label}',
  noTarget: 'अभी कोई नहीं चुना।',
  needTarget: 'इस चैट का एजेंट चुनने के लिए /agents इस्तेमाल करें।',
  targetSet: 'अब यहाँ जो लिखेंगे वह इसी एजेंट को जाएगा।',
  logEmpty: 'अभी कुछ दर्ज नहीं हुआ।',
  stopRequested: 'रोकने को कहा गया।',
  stopFailed: 'रोका नहीं जा सका।',
  sendNoAgent: 'वह एजेंट नहीं मिला। /agents से दूसरा चुनें।',
  sendReadOnly: 'यह एजेंट सिर्फ़ पढ़ने के लिए है (बाहरी हुक का सेशन)।',
  sendServerError: 'सर्वर ने {status} लौटाया।',
};

const id: ChatStrings = {
  titlePermission: 'Perlu izin',
  titleQuestion: 'Pertanyaan agen',
  titleReport: 'Laporan kerja',
  titleReview: 'Siap diperiksa',
  titleGoal: 'Sasaran',
  titleStreamText: 'Balasan',
  titleStreamThinking: 'Sedang berpikir',
  titleStreamTool: 'Alat',
  titleHelp: 'Cara pakai',
  titlePaired: 'Terhubung',
  titleNotPairing: 'Tidak menerima koneksi',
  titleDmOnly: 'Hanya lewat pesan langsung',
  titleUnpaired: 'Terputus',
  titleNoAgents: 'Tidak ada agen',
  titlePickAgent: 'Pilih agen',
  titleTargetSet: 'Agen dipilih',
  titleNeedTarget: 'Pilih agen dulu',
  titleStatus: 'Kemajuan',
  titleStop: 'Hentikan',
  titleSent: 'Terkirim',
  titleCannotSend: 'Tidak bisa dikirim',
  titleSendFailed: 'Gagal terkirim',
  titleLog: '{count} baris mentah terakhir',
  btnAllow: 'Izinkan',
  btnDeny: 'Tolak',
  permTool: 'Alat: {tool}',
  permRisk: 'Risiko: {risks}',
  permAutoIn: 'Diputuskan otomatis dalam {seconds} detik kalau tidak dijawab.',
  askFirstOf: '(pertama dari {count} pertanyaan)',
  reportUserActions: 'Yang perlu kamu kerjakan',
  reportDid: 'Sudah dikerjakan',
  reportNext: 'Berikutnya',
  reviewInstruction: 'Diminta: {text}',
  reviewChanges: 'Yang diubah',
  reviewCheckpoints: 'Yang perlu dicek',
  goalSteps: '{done}/{total} langkah · {percent}%',
  goalPercent: '{percent}%',
  goalNone: 'Belum ada sasaran saat ini.',
  goalQueued: '{count} perintah dalam antrean',
  streamUnnamedTool: '(tanpa nama)',
  helpNotPaired1: 'Obrolan ini belum terhubung.',
  helpNotPaired2: 'Buka File → Remote Control di Vibisual lalu pindai QR-nya.',
  helpAgents: '/agents — pilih agen yang diajak bicara di obrolan ini',
  helpStatus: '/status — sedang mengerjakan apa dan sampai mana',
  helpLog: '/log [n] — n baris mentah terakhir (bawaan {default}, maks {max})',
  helpStop: '/stop — hentikan giliran yang sedang jalan',
  helpUnpair: '/unpair — putuskan obrolan ini',
  helpPlain: 'Teks lain akan dikirim ke agen terpilih sebagai perintah.',
  pairNotOpen1: 'Saat ini tidak ada koneksi baru yang diterima.',
  pairNotOpen2: 'Buat QR baru dari File → Remote Control di desktop.',
  pairDmOnly1: 'Pemasangan hanya diterima lewat pesan langsung satu lawan satu.',
  pairDmOnly2: 'Kirim baris yang sama ke bot lewat DM, bukan di kanal bersama.',
  ackExpired: 'Permintaan itu sudah kedaluwarsa atau sudah ditangani.',
  ackAllowed: 'Diizinkan.',
  ackDenied: 'Ditolak.',
  ackAnswered: 'Dijawab dengan "{label}".',
  ackTooLate: 'Terlambat — sudah diputuskan otomatis.',
  unpairDone: 'Obrolan ini tidak akan menerima pemberitahuan lagi.',
  noAgents: 'Belum ada agen yang bisa menerima perintah.',
  currentTarget: 'Agen sekarang: {label}',
  noTarget: 'Belum ada yang dipilih.',
  needTarget: 'Pakai /agents untuk memilih agen obrolan ini.',
  targetSet: 'Mulai sekarang tulisanmu di sini dikirim ke agen ini.',
  logEmpty: 'Belum ada yang tercatat.',
  stopRequested: 'Permintaan berhenti dikirim.',
  stopFailed: 'Tidak bisa dihentikan.',
  sendNoAgent: 'Agen itu sudah tidak ada. Pilih yang lain dengan /agents.',
  sendReadOnly: 'Agen ini hanya-baca (sesi hook dari luar).',
  sendServerError: 'Server menjawab {status}.',
};

const TABLE: Record<UiLocale, ChatStrings> = {
  en, ko, ja, 'zh-CN': zhCN, es, 'es-419': es419, fr, de, hi, id, it, 'pt-BR': ptBR,
};

/**
 * 그 언어의 문자열 한 벌. 모르는 값이면 `en` 으로 떨어진다
 * (스냅샷이 아직 안 왔을 때도 여기로 온다 — 봇이 침묵하는 것보다 영어로 말하는 편이 낫다).
 */
export function chatStrings(locale: string | null | undefined): ChatStrings {
  if (locale && (SUPPORTED_UI_LOCALES as readonly string[]).includes(locale)) {
    return TABLE[locale as UiLocale];
  }
  return TABLE[DEFAULT_UI_LOCALE];
}

/**
 * `{이름}` 자리표시자를 채운다. 값이 없는 자리표시자는 **그대로 둔다** —
 * 지우면 문장이 조용히 뜻을 잃지만, 남아 있으면 어느 키가 빠졌는지 화면에서 바로 보인다.
 */
export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) => {
    const v = vars[key];
    return v === undefined ? whole : String(v);
  });
}
